# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dj', '0001_initial'),
        ('komponenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='komponenty',
            field=models.OneToOneField(db_column='komponenty', on_delete=django.db.models.deletion.CASCADE, related_name='dokumentacni_jednotka', to='komponenta.komponentavazby'),
        ),
    ]
