# Generated by Django 3.1.3 on 2021-04-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0001_initial'),
        ('pian', '0001_initial'),
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='pian',
            field=models.ForeignKey(blank=True, db_column='pian', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pian.pian'),
        ),
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='typ',
            field=models.ForeignKey(db_column='typ', limit_choices_to={'nazev_heslare': 34}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumentacni_jednotka_typy', to='heslar.heslar'),
        ),
    ]
