# Generated by Django 5.0.6 on 2024-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.dj.migrations.0006_alter_dokumentacnijednotka_negativni_jednotka`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("dj", "0005_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokumentacnijednotka",
            name="negativni_jednotka",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
