# Generated by Django 5.0.6 on 2024-05-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj", "0005_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokumentacnijednotka",
            name="negativni_jednotka",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
