# Generated by Django 3.2.11 on 2023-01-31 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifikace_projekty_pes',
            },
        ),
        migrations.AddIndex(
            model_name='pes',
            index=models.Index(fields=['content_type', 'object_id'], name='notifikace__content_d99450_idx'),
        ),
        migrations.AddConstraint(
            model_name='pes',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_pes'),
        ),
    ]
