FROM ubuntu:18.04
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN apt-get update --fix-missing
RUN apt-get install -y wget \
	bzip2 \
	ca-certificates \
	build-essential \
	curl \
	git-core \
	pkg-config \
	python3-dev \
	python3-pip \
	python3-setuptools \
	python3-virtualenv \
	unzip \
	software-properties-common \
	llvm

RUN apt install -y gdal-bin python-gdal python3-gdal
RUN pip3 install --upgrade pip

COPY /webclient/requirements/ .

RUN pip install -r dev.txt

## Setp filesystem
RUN mkdir /code
WORKDIR /code
COPY . /code/
