FROM postgis/postgis:14-3.3
VOLUME /tmp

ARG VERSION_APP
ARG TAG_APP

ENV VERSION=$VERSION_APP
ENV TAG=$TAG_APP

ENV FILE=backup_file_db_v4.tar

COPY ${FILE} /tmp/${FILE}
RUN echo ${FILE}
COPY /scripts/restore_database.sh /docker-entrypoint-initdb.d/restore_database.sh
RUN sed -i 's/\r$//g' /docker-entrypoint-initdb.d/restore_database.sh
RUN chmod 777 /docker-entrypoint-initdb.d/restore_database.sh

EXPOSE 5432
