FROM ubuntu:latest


ENV VERSION=${VERSION_APP}
ENV TAG=${TAG_APP}

RUN apt-get update && apt-get --assume-yes --no-install-recommends install openvpn ssh dnsutils iputils-ping
RUN mkdir /code
WORKDIR /code
COPY .github/vpn/  .github/vpn/
COPY scripts/ci_deployment/   scripts/
RUN chmod +x ./scripts/test_deployment.sh
RUN mkdir -p ~/.ssh &&  chmod 700 ~/.ssh && cat .github/vpn/SSH_KNOWN_HOST.txt >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
CMD ["./scripts/test_deployment.sh"]
