FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.1 AS system-deps

ENV DEBIAN_FRONTEND=noninteractive \
    TZ="Europe/Prague"

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3-dev \
        build-essential \
        gcc \
        libpq-dev \
        tzdata \
        cron \
        sudo \
        nano \
        libgdal-dev \
        locales \
        gettext \
        poppler-utils \
        unrar \
        redis-tools \
        libmagic1 \
    && locale-gen cs_CZ.utf8 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

FROM system-deps AS python-builder

COPY ./webclient/requirements.txt /tmp/requirements.txt

RUN pip3 wheel --no-cache-dir --wheel-dir /wheels -r /tmp/requirements.txt

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.1 AS dev-runtime

ARG VERSION_APP
ARG TAG_APP

ENV VERSION=$VERSION_APP \
    TAG=$TAG_APP \
    DEV_CONTAINER=1 \
    TZ="Europe/Prague" \
    LC_ALL="cs_CZ.utf8" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
        tzdata \
        cron \
        sudo \
        nano \
        python3 \
        python3-pip \
        libgdal-dev \
        locales \
        gettext \
        poppler-utils \
        unrar \
        redis-tools \
        libmagic1 \
    && locale-gen cs_CZ.utf8 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=python-builder /wheels /wheels
RUN pip3 install --no-cache-dir --no-index --find-links=/wheels /wheels/* --break-system-packages --ignore-installed \
    && rm -rf /wheels ~/.cache/pip

RUN echo "alias python=python3" >> /etc/bash.bashrc && \
    echo "alias pip=pip3" >> /etc/bash.bashrc

RUN mkdir -p /code \
             /vol/web/media \
             /vol/web/static \
             /vol/web/locale \
             /vol/web/nginx/data

COPY ./webclient /code
COPY ./scripts /scripts
COPY ./cert /cert
ADD ./proxy/custom_html /vol/web/nginx/data

WORKDIR /code

RUN userdel ubuntu && \
    adduser --disabled-password --gecos "" user && \
    passwd -d user && \
    usermod -aG sudo user && \
    chown -R user:user /vol /scripts /code && \
    chmod -R 755 /vol/web /scripts && \
    chmod 777 -R /vol/web/nginx/data && \
    chmod 777 -R /cert/amcr-test-local.crt && \
    chmod 777 -R /cert/amcr-test-local.key && \
    crontab -u user /scripts/crontab.txt

RUN echo "DATE:$(date +%Y%m%dT%H%M%S),VERSION:${VERSION}" > /version.txt

USER user
CMD ["entrypoint.dev.sh"]
