FROM node:25-bookworm-slim AS node-modules

WORKDIR /node_modules_build
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.13.0 AS python-builder

ENV DEBIAN_FRONTEND=noninteractive \
    TZ="Europe/Prague"

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3-dev \
        build-essential \
        gcc \
        libpq-dev \
        tzdata \
        cron \
        sudo \
        nano \
        libgdal-dev \
        locales \
        gettext \
        poppler-utils \
        unrar \
        redis-tools \
        libmagic1 \
        libcrypt-dev && \
    locale-gen cs_CZ.utf8 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./webclient/requirements.txt /tmp/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 wheel --wheel-dir /wheels -r /tmp/requirements.txt

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.13.0 AS runtime

ARG VERSION_APP
ARG TAG_APP

ENV VERSION=$VERSION_APP \
    TAG=$TAG_APP \
    DEV_CONTAINER=1 \
    TZ="Europe/Prague" \
    LC_ALL="cs_CZ.utf8" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN echo $TZ > /etc/timezone && \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    tzdata \
    cron \
    sudo \
    nano \
    python3 \
    python3-pip \
    libgdal-dev \
    locales \
    gettext \
    poppler-utils \
    unrar \
    redis-tools \
    libmagic1 && \
    locale-gen cs_CZ.utf8 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=python-builder /wheels /wheels
RUN pip3 install --no-cache-dir --no-index --find-links=/wheels /wheels/* --break-system-packages --ignore-installed && \
    rm -rf /wheels ~/.cache/pip

COPY --from=node-modules /node_modules_build/node_modules /node_modules
COPY ./package.json ./package-lock.json /

RUN echo -e "alias python=python3\nalias pip=pip3" >> /etc/bash.bashrc

RUN mkdir -p /vol/web/media /vol/web/static /vol/web/locale /vol/web/nginx/data && \
    userdel ubuntu && \
    adduser --disabled-password --gecos "" user && \
    passwd -d user && \
    usermod -aG sudo user

WORKDIR /code
#COPY --chown=user:user ./webclient /code
COPY --chown=user:user ./scripts /scripts
COPY --chown=user:user ./cert /cert
ADD --chown=user:user ./proxy/custom_html /vol/web/nginx/data

RUN chmod -R 755 /vol/web /scripts && \
    chmod 777 -R /vol/web/nginx/data /cert/amcr-test-local.crt /cert/amcr-test-local.key && \
    crontab -u user /scripts/crontab.txt && \
    echo "DATE:$(date +%Y%m%dT%H%M%S),VERSION:${VERSION}" > /version.txt

USER user
CMD ["entrypoint.dev.sh"]
