### from https://github.com/OSGeo/gdal/tree/master/docker ###
# Use latest gdal official image
FROM ghcr.io/osgeo/gdal:ubuntu-small-3.9.1

# Load arguments
ARG VERSION_APP
ARG TAG_APP
ARG DATE_CREATED
ARG REVISION

# Set variables
ENV VERSION=${VERSION_APP}
ENV TAG=${TAG_APP}

# Set labels
LABEL org.opencontainers.image.title="Archaeological Map of the Czech Republic (AMCR)"
LABEL org.opencontainers.image.description="The Archaeological Map of the Czech Republic (AMCR) is an information system for the collection, management and presentation of data on archaeological fieldwork in the Czech Republic and for supporting related workflows."
LABEL org.opencontainers.image.url=https://github.com/ARUP-CAS/aiscr-webamcr
LABEL org.opencontainers.image.source=https://github.com/ARUP-CAS/aiscr-webamcr
LABEL org.opencontainers.image.version=${VERSION_APP}
LABEL org.opencontainers.image.created=${DATE_CREATED}
LABEL org.opencontainers.image.revision=${REVISION}
LABEL org.opencontainers.image.authors="Archaeological Information System of the Czech Republic (AIS CR)"
LABEL org.opencontainers.image.licenses=AGPL-3.0-or-later
LABEL org.opencontainers.image.documentation="https://aiscr-webamcr.readthedocs.io/"

# Update base container install
RUN apt-get clean

# Configure timezone
ENV TZ="Europe/Prague"
RUN echo $TZ > /etc/timezone
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

# Install dependencies
RUN apt-get -qq -y install cron && apt-get -y -qq install sudo
RUN apt-get install -y python3-pip libgdal-dev locales gettext poppler-utils unrar jq postgresql-client curl redis-tools

# Ensure locales configured correctly
RUN locale-gen cs_CZ.utf8
ENV LC_ALL='cs_CZ.utf8'

# Set python aliases for python3
RUN echo 'alias python=python3' >> ~/.bashrc
RUN echo 'alias pip=pip3' >> ~/.bashrc

# Set paths
ENV PATH="/scripts:${PATH}"

# Install Python dependencies
COPY ./webclient/requirements.txt .
RUN pip3 install -r requirements.txt --break-system-packages

# Set up application files
RUN mkdir /code
COPY ./webclient /code
WORKDIR /code
COPY ./scripts /scripts
RUN chmod +x /scripts/*

# Uploaded images
RUN mkdir -p /vol/web/media

# Staic files for the app
RUN mkdir -p /vol/web/static

# locales for translations
RUN mkdir -p /vol/web/locale/cs/LC_MESSAGES
RUN mkdir -p /vol/web/locale/en/LC_MESSAGES

# Create non-root user and set permissions
RUN userdel ubuntu
RUN adduser user
RUN passwd -d user
RUN usermod -aG sudo user
RUN chown -R user:user /vol
RUN chmod -R 755 /vol/web
RUN chown -R user:user /code
RUN chmod -R 755 /code

# Apply cron and update templates
RUN crontab -u user /scripts/crontab.txt
RUN echo "DATE:$(date +%Y%m%dT%H%M%S),VERSION:${VERSION}" > /version.txt
RUN sed -i "s/1.0.0/${VERSION}/g" ./templates/base_logged_in.html
RUN current_year=$(date +%Y) && \
    sed -i "s/YYYY/${current_year}/g" ./templates/base_logged_in.html

# Set entrypoint and user
USER user
CMD ["entrypoint.sh"]
