# Generated by Django 3.1.3 on 2021-02-08 09:27

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historie', '0001_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.SmallIntegerField(choices=[(0, 'Oznámen'), (1, 'Zapsán'), (2, 'Přihlášen'), (3, 'Zahájen v terénu'), (4, 'Ukončen v terénu'), (5, 'Uzavřen'), (6, 'Archivován'), (7, 'Nevržen ke zrušení'), (8, 'Zrušen')], default=0)),
                ('lokalizace', models.TextField(blank=True, null=True)),
                ('kulturni_pamatka_cislo', models.TextField(blank=True, null=True)),
                ('kulturni_pamatka_popis', models.TextField(blank=True, null=True)),
                ('parcelni_cislo', models.TextField(blank=True, null=True)),
                ('podnet', models.TextField(blank=True, null=True)),
                ('uzivatelske_oznaceni', models.TextField(blank=True, null=True)),
                ('datum_zahajeni', models.DateField(blank=True, null=True)),
                ('datum_ukonceni', models.DateField(blank=True, null=True)),
                ('planovane_zahajeni_text', models.TextField(blank=True, null=True)),
                ('termin_odevzdani_nz', models.DateField(blank=True, null=True)),
                ('ident_cely', models.TextField(blank=True, null=True, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('oznaceni_stavby', models.TextField(blank=True, null=True)),
                ('planovane_zahajeni', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('historie', models.ForeignKey(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.CASCADE, to='historie.historievazby')),
            ],
            options={
                'verbose_name': 'projekty',
                'db_table': 'projekt',
            },
        ),
        migrations.CreateModel(
            name='ProjektKatastr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hlavni', models.BooleanField(default=False)),
                ('katastr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heslar.ruiankatastr')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.projekt')),
            ],
            options={
                'db_table': 'projekt_katastr',
            },
        ),
        migrations.AddField(
            model_name='projekt',
            name='katastry',
            field=models.ManyToManyField(through='projekt.ProjektKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='kulturni_pamatka',
            field=models.ForeignKey(blank=True, db_column='kulturni_pamatka', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
    ]
