# Generated by Django 3.1.3 on 2021-02-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekt', '0001_initial'),
        ('oznameni', '0001_initial'),
        ('heslar', '0001_initial'),
        ('core', '0002_auto_20210208_1027'),
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='organizace',
            field=models.ForeignKey(blank=True, db_column='organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='oznamovatel',
            field=models.ForeignKey(blank=True, db_column='oznamovatel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oznameni.oznamovatel'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='soubory',
            field=models.ForeignKey(blank=True, db_column='soubory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.souborvazby'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='typ_projektu',
            field=models.ForeignKey(db_column='typ_projektu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekty_typu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='vedouci_projektu',
            field=models.ForeignKey(blank=True, db_column='vedouci_projektu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AlterUniqueTogether(
            name='projekt',
            unique_together={('id', 'oznamovatel')},
        ),
    ]
