# Generated by Django 3.1.3 on 2021-01-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projekt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projekt",
            options={"verbose_name": "projekty"},
        ),
    ]
