# Generated by Django 3.2.11 on 2022-05-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0002_auto_20220527_0924'),
        ('projekt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='datum_ukonceni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum ukončení'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='datum_zahajeni',
            field=models.DateField(blank=True, null=True, verbose_name='Datum zahájení'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='hlavni_katastr',
            field=models.ForeignKey(db_column='hlavni_katastr', on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekty_hlavnich_katastru', to='heslar.ruiankatastr', verbose_name='Hlavní katastr'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='ident_cely',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Identifikátor'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='kulturni_pamatka',
            field=models.ForeignKey(blank=True, db_column='kulturni_pamatka', limit_choices_to={'nazev_heslare': 10}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar', verbose_name='Památka'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='oznaceni_stavby',
            field=models.TextField(blank=True, null=True, verbose_name='Označení stavby'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='podnet',
            field=models.TextField(blank=True, null=True, verbose_name='Podnět'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='stav',
            field=models.SmallIntegerField(choices=[(0, 'P0 - Oznámen'), (1, 'P1 - Zapsán'), (2, 'P2 - Přihlášen'), (3, 'P3 - Zahájen v terénu'), (4, 'P4 - Ukončen v terénu'), (5, 'P5 - Uzavřen'), (6, 'P6 - Archivován'), (7, 'P7 - Navržen ke zrušení'), (8, 'P8 - Zrušen')], default=0, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='typ_projektu',
            field=models.ForeignKey(db_column='typ_projektu', limit_choices_to={'nazev_heslare': 41}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekty_typu', to='heslar.heslar', verbose_name='Typ projektů'),
        ),
    ]
