# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.projekt.migrations.0003_triggers`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    initial = True

    dependencies = [
        ("projekt", "0002_initial"),
        ("pas", "0001_initial"),
        ("dokument", "0001_initial"),
    ]

    operations = [
    ]
