# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekt', '0002_initial'),
        ('pas', '0001_initial'),
        ('dokument', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.prevent_project_deletion()
                RETURNS trigger
                LANGUAGE 'plpgsql'
                COST 100
                VOLATILE NOT LEAKPROOF
            AS $BODY$
                    BEGIN
                        IF EXISTS (SELECT FROM soubor_vazby AS sv inner join soubor AS s ON s.vazba = sv.id WHERE s.projekt = OLD.id) THEN
                            RAISE EXCEPTION 'Nelze smazat projekt s projektovou dokumentací!';
                        END IF;
                        RETURN OLD;
                    END;    
            $BODY$;
            """,
            reverse_sql="DROP FUNCTION public.prevent_project_deletion;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER prevent_project_deletion
                BEFORE DELETE
                ON projekt
                FOR EACH ROW
                EXECUTE FUNCTION prevent_project_deletion();
            """,
            reverse_sql="DROP TRIGGER public.prevent_project_deletion;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.delete_related_soubor()
                RETURNS trigger
                LANGUAGE 'plpgsql'
                COST 100
                VOLATILE NOT LEAKPROOF
            AS $BODY$
                BEGIN
                    DELETE FROM soubor_vazby WHERE soubor_vazby.id = old.soubory;
                    RETURN NEW;
                END;   
            $BODY$;
            """,
            reverse_sql="DROP FUNCTION public.delete_related_soubor;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor_projekt
                AFTER DELETE
                ON projekt
                FOR EACH ROW
                EXECUTE FUNCTION delete_related_soubor();
            """,
            reverse_sql="DROP TRIGGER public.delete_related_soubor_projekt;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor_samostatny_nalez
                AFTER DELETE
                ON samostatny_nalez
                FOR EACH ROW
                EXECUTE FUNCTION delete_related_soubor();
            """,
            reverse_sql="DROP TRIGGER public.delete_related_soubor_samostatny_nalez;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor_dokument
                AFTER DELETE
                ON dokument
                FOR EACH ROW
                EXECUTE FUNCTION delete_related_soubor();
            """,
            reverse_sql="DROP TRIGGER public.delete_related_soubor_dokument;",
        ),
    ]
