# Generated by Django 3.1.3 on 2021-02-18 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oznameni', '0001_initial'),
        ('heslar', '0003_ruiankatastr_soucasny'),
        ('projekt', '0002_auto_20210215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='oznamovatel',
            field=models.OneToOneField(blank=True, db_column='oznamovatel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='oznameni.oznamovatel'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='typ_projektu',
            field=models.ForeignKey(db_column='typ_projektu', limit_choices_to={'nazev_heslare': 41}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projekty_typu', to='heslar.heslar'),
        ),
    ]
