# Generated by Django 4.1.7 on 2023-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0005_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projekt",
            name="stav",
            field=models.SmallIntegerField(
                choices=[
                    (0, "P0 - Oznámen"),
                    (1, "P1 - Zapsán"),
                    (2, "P2 - Přihlášen"),
                    (3, "P3 - Zahájen v terénu"),
                    (4, "P4 - Ukončen v terénu"),
                    (5, "P5 - Uzavřen"),
                    (6, "P6 - Archivován"),
                    (7, "P7 - Navržen ke zrušení"),
                    (8, "P8 - Zrušen"),
                ],
                db_index=True,
                default=0,
                verbose_name="Stav",
            ),
        ),
    ]
