# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("heslar", "0005_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
        ("projekt", "0006_alter_projekt_stav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projekt",
            name="typ_projektu",
            field=models.ForeignKey(
                db_column="typ_projektu",
                limit_choices_to={"nazev_heslare": 41},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="projekty_typu",
                to="heslar.heslar",
                verbose_name="Typ projektů",
            ),
        ),
    ]
