# Generated by Django 5.1.4 on 2025-01-03 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.projekt.migrations.0009_projekt_geom_sjtsk_projekt_geom_system``."""
    dependencies = [
        ("projekt", "0008_alter_projekt_datum_ukonceni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projekt",
            name="geom_sjtsk",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=5514
            ),
        ),
        migrations.AddField(
            model_name="projekt",
            name="geom_system",
            field=models.CharField(default="5514", max_length=6),
        ),
    ]
