# Generated by Django 5.1.5 on 2025-03-01 19:57

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.projekt.migrations.0010_projekt_pristupnost_snapshot``."""
    atomic = False

    dependencies = [
        ("heslar", "0009_alter_heslar_razeni"),
        ("projekt", "0009_projekt_geom_sjtsk_projekt_geom_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="projekt",
            name="pristupnost_snapshot",
            field=models.ForeignKey(
                limit_choices_to={"nazev_heslare": 25},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="projekty",
                to="heslar.heslar",
            ),
        ),

    ]
