# Generated by Django 5.1.5 on 2025-03-01 19:57

import django.db.models.deletion
from django.db import migrations, models, transaction

from projekt.models import Projekt


BATCH_SIZE = 100


def set_pristupnost_snapshot(apps, schema_editor):
    projekt_count = Projekt.objects.all().count()
    for i in range(projekt_count//BATCH_SIZE - 1):
        with transaction.atomic():
            projekty = list(Projekt.objects.all())[i*BATCH_SIZE:(i+1)*BATCH_SIZE]
            for projekt in projekty:
                projekt.suppress_signal = True
                projekt.set_pristupnost()
            Projekt.objects.bulk_update(projekty, ["pristupnost_snapshot"])

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("heslar", "0009_alter_heslar_razeni"),
        ("projekt", "0009_projekt_geom_sjtsk_projekt_geom_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="projekt",
            name="pristupnost_snapshot",
            field=models.ForeignKey(
                limit_choices_to={"nazev_heslare": 25},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="projekty",
                to="heslar.heslar",
            ),
        ),
        migrations.RunPython(set_pristupnost_snapshot),
    ]
