# Generated by Django 5.2.11 on 2026-03-16 08:33

from django.db import migrations, models


BACKFILL_SQL = """
UPDATE projekt p
SET datum_uzavreni = (
    SELECT h.datum_zmeny::date
    FROM historie h
    JOIN historie_vazby hv ON h.vazba = hv.id
    WHERE hv.id = p.historie
      AND h.typ_zmeny = 'P45'
    ORDER BY h.datum_zmeny DESC
    LIMIT 1
)
WHERE p.datum_uzavreni IS NULL;

UPDATE projekt p
SET datum_prihlaseni = (
    SELECT h.datum_zmeny::date
    FROM historie h
    JOIN historie_vazby hv ON h.vazba = hv.id
    WHERE hv.id = p.historie
      AND h.typ_zmeny = 'P12'
    ORDER BY h.datum_zmeny DESC
    LIMIT 1
)
WHERE p.datum_prihlaseni IS NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_projekt_pristupnost_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='datum_prihlaseni',
            field=models.DateField(blank=True, null=True, verbose_name='projekt.models.projekt.datumPrihlaseni.label'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='datum_uzavreni',
            field=models.DateField(blank=True, null=True, verbose_name='projekt.models.projekt.datumUzavreni.label'),
        ),
        migrations.RunSQL(BACKFILL_SQL, migrations.RunSQL.noop),
    ]
