from typing import Final

# Stavy projektu
PROJEKT_STAV_OZNAMENY: Final = 0
PROJEKT_STAV_REGISTROVANY: Final = 1
PROJEKT_STAV_PRIHLASENY: Final = 2
PROJEKT_STAV_ZAHAJENY: Final = 3
PROJEKT_STAV_UKONCENY: Final = 4
PROJEKT_STAV_NAVRZEN_K_ARCHIVACI: Final = 5
PROJEKT_STAV_ARCHIVOVANY: Final = 6
PROJEKT_STAV_NAVRZEN_KE_ZRUSENI: Final = 7
PROJEKT_STAV_ZRUSENY: Final = 8
