# Generated by Django 3.1.3 on 2021-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pian',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'Nepotvrzený'), (2, 'Potvrzený')]),
        ),
    ]
