# Generated by Django 3.2.11 on 2022-05-27 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pian',
            name='geom_sjtsk',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=5514),
        ),
        migrations.AddField(
            model_name='pian',
            name='geom_system',
            field=models.TextField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
