# Generated by Django 3.2.11 on 2023-02-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kladyzm',
            name='nazev',
        ),
    ]
