# Generated by Django 4.1.7 on 2023-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pian", "0003_views"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="piansekvence",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="piansekvence",
            constraint=models.UniqueConstraint(
                fields=("kladyzm50", "katastr"), name="unique_sekvence_pian"
            ),
        ),
    ]
