# Generated by Django 4.2.11 on 2024-04-04 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pian", "0004_alter_piansekvence_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pian",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                db_index=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="pian",
            name="geom_sjtsk",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, db_index=True, null=True, srid=5514
            ),
        ),
        migrations.AlterField(
            model_name="pian",
            name="geom_system",
            field=models.CharField(db_index=True, default="4326", max_length=6),
        ),
        migrations.AlterField(
            model_name="pian",
            name="stav",
            field=models.SmallIntegerField(
                choices=[
                    (1, "pian.models.pian.states.nepotvrzen"),
                    (2, "pian.models.pian.states.potvrzen"),
                ],
                db_index=True,
                default=1,
            ),
        ),
    ]
