# Generated by Django 5.1.2 on 2024-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.pian.migrations.0006_remove_pian_pian_geom_check_alter_pian_geom_system_and_more``."""
    dependencies = [
        ('heslar', '0007_alter_heslar_unique_together_and_more'),
        ('historie', '0009_alter_historie_typ_zmeny'),
        ('pian', '0005_views'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pian',
            name='pian_geom_check',
        ),
        migrations.AlterField(
            model_name='pian',
            name='geom_system',
            field=models.CharField(db_index=True, default='5514', max_length=6),
        ),
        migrations.AddConstraint(
            model_name='pian',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('geom_system', '5514'), ('geom_sjtsk__isnull', False)), models.Q(('geom_system', '4326'), ('geom__isnull', False)), models.Q(('geom_sjtsk__isnull', True), ('geom__isnull', True)), _connector='OR'), name='pian_geom_check'),
        ),
    ]
