# Generated by Django 5.1.4 on 2025-01-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.pian.migrations.0007_remove_pian_geom_sjtsk_updated_at_and_more`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ('pian', '0006_remove_pian_pian_geom_check_alter_pian_geom_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pian',
            name='geom_sjtsk_updated_at',
        ),
        migrations.RemoveField(
            model_name='pian',
            name='geom_updated_at',
        ),
    ]
