# Generated by Django 3.2.11 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komponenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenta',
            name='jistota',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
