# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.komponenta.migrations.0002_triggers`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    initial = True

    dependencies = [
        ("komponenta", "0001_initial"),
        ("nalez", "0001_initial"),
    ]

    operations = [
    ]
