# Generated by Django 3.2.11 on 2022-12-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projekt', '0001_initial'),
        ('historie', '0002_initial'),
        ('uzivatel', '0001_initial'),
        ('pas', '0001_initial'),
        ('core', '0003_soubor_vlastnik'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatelspoluprace',
            name='spolupracovnik',
            field=models.ForeignKey(db_column='spolupracovnik', on_delete=django.db.models.deletion.DO_NOTHING, related_name='spoluprace_badatelu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzivatelspoluprace',
            name='vedouci',
            field=models.ForeignKey(db_column='vedouci', on_delete=django.db.models.deletion.DO_NOTHING, related_name='spoluprace_archeologu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='druh_nalezu',
            field=models.ForeignKey(blank=True, db_column='druh_nalezu', limit_choices_to={'nazev_heslare': 22}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy_druhu_predmetu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='historie',
            field=models.OneToOneField(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sn_historie', to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='katastr',
            field=models.ForeignKey(blank=True, db_column='katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='nalezce',
            field=models.ForeignKey(blank=True, db_column='nalezce', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='obdobi',
            field=models.ForeignKey(blank=True, db_column='obdobi', limit_choices_to={'nazev_heslare': 15}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy_obdobi', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='okolnosti',
            field=models.ForeignKey(blank=True, db_column='okolnosti', limit_choices_to={'nazev_heslare': 14}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy_okolnosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='predano_organizace',
            field=models.ForeignKey(blank=True, db_column='predano_organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='projekt',
            field=models.ForeignKey(db_column='projekt', limit_choices_to={'typ_projektu': 1136}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy', to='projekt.projekt'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='soubory',
            field=models.OneToOneField(blank=True, db_column='soubory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatny_nalez_souboru', to='core.souborvazby'),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='specifikace',
            field=models.ForeignKey(blank=True, db_column='specifikace', limit_choices_to={'nazev_heslare': 30}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy_specifikace', to='heslar.heslar'),
        ),
        migrations.AlterUniqueTogether(
            name='uzivatelspoluprace',
            unique_together={('vedouci', 'spolupracovnik')},
        ),
    ]
