# Generated by Django 3.1.3 on 2021-04-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('projekt', '0002_auto_20210317_1819'),
        ('pas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samostatnynalez',
            name='katastr',
            field=models.ForeignKey(blank=True, db_column='katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy', to='heslar.ruiankatastr'),
        ),
        migrations.AlterField(
            model_name='samostatnynalez',
            name='projekt',
            field=models.ForeignKey(db_column='projekt', on_delete=django.db.models.deletion.DO_NOTHING, related_name='samostatne_nalezy', to='projekt.projekt'),
        ),
        migrations.AlterField(
            model_name='samostatnynalez',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'zapsaný'), (2, 'odeslaný'), (3, 'potvrzený'), (4, 'archivovaný')]),
        ),
    ]
