# Generated by Django 3.2.11 on 2022-05-27 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samostatnynalez',
            name='geom_sjtsk',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='samostatnynalez',
            name='geom_system',
            field=models.TextField(default='wgs84'),
        ),
    ]
