# Generated by Django 3.2.11 on 2022-05-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0003_auto_20220527_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samostatnynalez',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'SN1 - zapsaný'), (2, 'SN2 - odeslaný'), (3, 'SN3 - potvrzený'), (4, 'SN4 - archivovaný')]),
        ),
    ]
