# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pas", "0003_default"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor_samostatny_nalez BEFORE DELETE ON samostatny_nalez
                FOR EACH ROW EXECUTE PROCEDURE delete_related_soubor();
            """,
            reverse_sql="""
            DROP TRIGGER public.delete_related_soubor_samostatny_nalez;
            """,
        ),
    ]
