# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.pas.migrations.0004_triggers``."""
    initial = True

    dependencies = [
        ("pas", "0003_default"),
    ]

    operations = [
    ]
