# Generated by Django 3.2.11 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0004_alter_samostatnynalez_stav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samostatnynalez',
            name='predano',
            field=models.BooleanField(blank=True, choices=[(True, 'Ano'), (False, 'Ne')], default=False, null=True),
        ),
    ]
