# Generated by Django 4.1.9 on 2023-06-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0006_alter_projekt_stav"),
        ("pas", "0004_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samostatnynalez",
            name="projekt",
            field=models.ForeignKey(
                db_column="projekt",
                limit_choices_to={"typ_projektu": 1138},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="samostatne_nalezy",
                to="projekt.projekt",
            ),
        ),
    ]
