# Generated by Django 4.2.3 on 2023-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pas", "0005_alter_samostatnynalez_projekt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samostatnynalez",
            name="predano",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Ano"), (False, "Ano")],
                default=False,
                null=True,
            ),
        ),
    ]
