# Generated by Django 5.1.2 on 2024-11-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customadminsettings_options_and_more'),
        ('heslar', '0007_alter_heslar_unique_together_and_more'),
        ('historie', '0009_alter_historie_typ_zmeny'),
        ('pas', '0006_views'),
        ('projekt', '0008_alter_projekt_datum_ukonceni_and_more'),
        ('uzivatel', '0016_organizace_cteni_dokumentu'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='samostatnynalez',
            name='samostatny_nalez_geom_check',
        ),
        migrations.AlterField(
            model_name='samostatnynalez',
            name='geom_system',
            field=models.TextField(default='5514'),
        ),
        migrations.AlterField(
            model_name='samostatnynalez',
            name='projekt',
            field=models.ForeignKey(db_column='projekt', limit_choices_to={'typ_projektu': 1137}, on_delete=django.db.models.deletion.RESTRICT, related_name='samostatne_nalezy', to='projekt.projekt'),
        ),
        migrations.AddConstraint(
            model_name='samostatnynalez',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('geom_system', '5514'), ('geom_sjtsk__isnull', False)), models.Q(('geom_system', '4326'), ('geom__isnull', False)), models.Q(('geom_sjtsk__isnull', True), ('geom__isnull', True)), _connector='OR'), name='samostatny_nalez_geom_check'),
        ),
    ]
