# Generated by Django 5.1.3 on 2024-12-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.pas.migrations.0008_samostatnynalez_igsn_alter_samostatnynalez_projekt``."""
    dependencies = [
        ("pas", "0007_remove_samostatnynalez_samostatny_nalez_geom_check_and_more"),
        ("projekt", "0008_alter_projekt_datum_ukonceni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="samostatnynalez",
            name="igsn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
