# Generated by Django 5.1.4 on 2025-01-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0007_remove_samostatnynalez_samostatny_nalez_geom_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samostatnynalez',
            name='geom_sjtsk_updated_at',
        ),
        migrations.RemoveField(
            model_name='samostatnynalez',
            name='geom_updated_at',
        ),
    ]
