# Generated by Django 5.1.3 on 2025-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.pas.migrations.0009_merge_20250112_1542``."""
    dependencies = [
        ("pas", "0008_remove_samostatnynalez_geom_sjtsk_updated_at_and_more"),
        ("pas", "0008_samostatnynalez_igsn_alter_samostatnynalez_projekt"),
    ]

    operations = []
