# Generated by Django 5.1.5 on 2025-02-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.pas.migrations.0010_alter_samostatnynalez_igsn_and_more`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("pas", "0009_merge_20250112_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samostatnynalez",
            name="igsn",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
