# Generated by Django 5.2.11 on 2026-03-28 07:12

from django.db import migrations, models


def populate_projekty(apps, schema_editor):
    """Naplní existující aktivní spolupráce aktuálně dostupnými průzkumnými projekty (P3+P4)."""
    UzivatelSpoluprace = apps.get_model("pas", "UzivatelSpoluprace")
    Projekt = apps.get_model("projekt", "Projekt")
    SPOLUPRACE_AKTIVNI = 2
    TYP_PROJEKTU_PRUZKUM_ID = 1135
    PROJEKT_STAV_ZAHAJENY_V_TERENU = 3
    PROJEKT_STAV_UKONCENY_V_TERENU = 4

    for sp in UzivatelSpoluprace.objects.filter(stav=SPOLUPRACE_AKTIVNI).select_related("vedouci__organizace"):
        projekty = Projekt.objects.filter(
            typ_projektu=TYP_PROJEKTU_PRUZKUM_ID,
            organizace=sp.vedouci.organizace,
            stav__in=[PROJEKT_STAV_ZAHAJENY_V_TERENU, PROJEKT_STAV_UKONCENY_V_TERENU],
        )
        sp.projekty.set(projekty)


class Migration(migrations.Migration):

    dependencies = [
        ("pas", "0011_alter_samostatnynalez_projekt"),
        ("projekt", "0011_projekt_datum_prihlaseni_projekt_datum_uzavreni"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzivatelspoluprace",
            name="projekty",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"typ_projektu": 1135},
                related_name="spoluprace_projektu",
                to="projekt.projekt",
                verbose_name="pas.models.uzivatelSpoluprace.projekty.label",
            ),
        ),
        migrations.RunPython(populate_projekty, migrations.RunPython.noop),
    ]
