# Generated by Django 6.0.1 on 2026-10-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0012_uzivatelspoluprace_projekty'),
        ('projekt', '0011_projekt_datum_prihlaseni_projekt_datum_uzavreni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samostatnynalez',
            name='projekt',
            field=models.ForeignKey(db_column='projekt', limit_choices_to={'typ_projektu': 1137}, on_delete=django.db.models.deletion.RESTRICT, related_name='samostatne_nalezy', to='projekt.projekt'),
        ),
    ]
