# Generated by Django 3.1.3 on 2021-06-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0001_initial'),
        ('arch_z', '0001_initial'),
        ('ez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externiodkaz',
            name='externi_zdroj',
            field=models.ForeignKey(blank=True, db_column='externi_zdroj', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='externi_odkazy_zdroje', to='ez.externizdroj'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='archeologicky_zaznam',
            field=models.ForeignKey(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='katastr',
            field=models.ForeignKey(db_column='katastr', on_delete=django.db.models.deletion.CASCADE, to='heslar.ruiankatastr'),
        ),
    ]
