# Generated by Django 3.1.3 on 2021-04-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0001_initial'),
        ('pian', '0001_initial'),
        ('arch_z', '0001_initial'),
        ('historie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='pian',
            field=models.ForeignKey(blank=True, db_column='pian', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pian.pian'),
        ),
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='typ',
            field=models.ForeignKey(db_column='typ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumentacni_jednotka_typy', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='archeologicky_zaznam',
            field=models.ForeignKey(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='katastr',
            field=models.ForeignKey(db_column='katastr', on_delete=django.db.models.deletion.CASCADE, to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='historie',
            field=models.ForeignKey(db_column='historie', on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(blank=True, db_column='hlavni_katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=857, limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
