# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0001_initial'),
        ('ez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externiodkaz',
            name='externi_zdroj',
            field=models.ForeignKey(db_column='externi_zdroj', on_delete=django.db.models.deletion.RESTRICT, related_name='externi_odkazy_zdroje', to='ez.externizdroj'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='archeologicky_zaznam',
            field=models.ForeignKey(db_column='archeologicky_zaznam_id', on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam'),
        ),
    ]
