# Generated by Django 3.1.3 on 2021-01-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_z", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="akce",
            name="final_cj",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="akce",
            name="je_nz",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="akce",
            name="odlozena_nz",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lokalita",
            name="final_cj",
            field=models.BooleanField(default=False),
        ),
    ]
