# Generated by Django 3.1.3 on 2021-05-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0001_initial'),
        ('historie', '0001_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='historie',
            field=models.ForeignKey(db_column='historie', on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(blank=True, db_column='hlavni_katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=857, limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
