# Generated by Django 3.1.3 on 2021-03-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='komponenty',
            field=models.ForeignKey(blank=True, db_column='komponenty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumentacni_jednotky', to='core.komponentavazby'),
        ),
    ]
