# Generated by Django 3.1.3 on 2021-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_z", "0002_auto_20210127_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archeologickyzaznam",
            name="typ_zaznamu",
            field=models.TextField(
                choices=[("L", "Lokalita"), ("A", "Akce")], max_length=1
            ),
        ),
    ]
