# Generated by Django 3.1.3 on 2021-07-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0001_initial'),
        ('historie', '0001_initial'),
        ('arch_z', '0002_auto_20210704_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='historie',
            field=models.ForeignKey(db_column='historie', on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(blank=True, db_column='hlavni_katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=863, limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
