# Generated by Django 3.1.3 on 2021-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0002_dokumentacnijednotka_komponenty'),
        ('pian', '0001_initial'),
        ('heslar', '0001_initial'),
        ('historie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='pian',
            field=models.ForeignKey(blank=True, db_column='pian', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pian.pian'),
        ),
        migrations.AddField(
            model_name='dokumentacnijednotka',
            name='typ',
            field=models.ForeignKey(db_column='typ', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumentacni_jednotka_typy', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='archeologicky_zaznam',
            field=models.ForeignKey(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznamkatastr',
            name='katastr',
            field=models.ForeignKey(db_column='katastr', on_delete=django.db.models.deletion.CASCADE, to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='historie',
            field=models.ForeignKey(db_column='historie', on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(blank=True, db_column='hlavni_katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=857, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='lokalita',
            name='druh',
            field=models.ForeignKey(db_column='druh', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lokality_druhy', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='lokalita',
            name='jistota',
            field=models.ForeignKey(blank=True, db_column='jistota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='lokalita',
            name='typ_lokality',
            field=models.ForeignKey(db_column='typ_lokality', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lokality_typu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='lokalita',
            name='zachovalost',
            field=models.ForeignKey(blank=True, db_column='zachovalost', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lokality_zachovalosti', to='heslar.heslar'),
        ),
        migrations.AlterUniqueTogether(
            name='archeologickyzaznamkatastr',
            unique_together={('archeologicky_zaznam', 'katastr')},
        ),
        migrations.AddField(
            model_name='akce',
            name='hlavni_typ',
            field=models.ForeignKey(blank=True, db_column='hlavni_typ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_hlavni_typy', to='heslar.heslar'),
        ),
    ]
