# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historie', '0001_initial'),
        ('heslar', '0002_initial'),
        ('arch_z', '0003_archeologickyzaznamkatastr_katastr'),
    ]

    operations = [
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='historie',
            field=models.OneToOneField(null=True, db_column='historie', on_delete=django.db.models.deletion.CASCADE, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(db_column='hlavni_katastr', on_delete=django.db.models.deletion.RESTRICT, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(blank=True, through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=863, limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.RESTRICT, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
