# Generated by Django 3.1.3 on 2021-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0003_auto_20210215_1659'),
        ('projekt', '0001_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akce',
            name='projekt',
            field=models.ForeignKey(blank=True, db_column='projekt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projekt.projekt'),
        ),
        migrations.AddField(
            model_name='akce',
            name='specifikace_data',
            field=models.ForeignKey(db_column='specifikace_data', on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_specifikace_data', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='akce',
            name='vedlejsi_typ',
            field=models.ForeignKey(blank=True, db_column='vedlejsi_typ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_vedlejsi_typy', to='heslar.heslar'),
        ),
    ]
