# Generated by Django 3.1.3 on 2021-02-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('arch_z', '0004_auto_20210208_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=1197, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
