# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekt', '0001_initial'),
        ('heslar', '0002_initial'),
        ('arch_z', '0004_initial'),
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcevedouci',
            name='organizace',
            field=models.ForeignKey(db_column='organizace', on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='akcevedouci',
            name='vedouci',
            field=models.ForeignKey(db_column='vedouci', on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.osoba'),
        ),
        migrations.AlterUniqueTogether(
            name='archeologickyzaznamkatastr',
            unique_together={('archeologicky_zaznam', 'katastr')},
        ),
        migrations.AddField(
            model_name='akcevedouci',
            name='akce',
            field=models.ForeignKey(db_column='akce', on_delete=django.db.models.deletion.CASCADE, to='arch_z.akce'),
        ),
        migrations.AddField(
            model_name='akce',
            name='hlavni_typ',
            field=models.ForeignKey(blank=True, db_column='hlavni_typ', limit_choices_to={'nazev_heslare': 32}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='akce_hlavni_typy', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='akce',
            name='hlavni_vedouci',
            field=models.ForeignKey(blank=True, db_column='hlavni_vedouci', null=True, on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='akce',
            name='organizace',
            field=models.ForeignKey(blank=True, db_column='organizace', null=True, on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='akce',
            name='projekt',
            field=models.ForeignKey(blank=True, db_column='projekt', null=True, on_delete=django.db.models.deletion.RESTRICT, to='projekt.projekt'),
        ),
        migrations.AddField(
            model_name='akce',
            name='specifikace_data',
            field=models.ForeignKey(db_column='specifikace_data', limit_choices_to={'nazev_heslare': 27}, on_delete=django.db.models.deletion.RESTRICT, related_name='akce_specifikace_data', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='akce',
            name='vedlejsi_typ',
            field=models.ForeignKey(blank=True, db_column='vedlejsi_typ', limit_choices_to={'nazev_heslare': 32}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='akce_vedlejsi_typy', to='heslar.heslar'),
        ),
        migrations.AlterUniqueTogether(
            name='akcevedouci',
            unique_together={('akce', 'vedouci')},
        ),
        migrations.AddConstraint(
            model_name='akce',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('typ', 'N'), ('projekt__isnull', True)),
                                                             models.Q(('typ', 'R'), ('projekt__isnull', False)),
                                                             _connector='OR'), name='akce_typ_check'),
        ),
        migrations.AddConstraint(
            model_name='archeologickyzaznam',
            constraint=models.CheckConstraint(
                check=models.Q(('typ_zaznamu', 'L'), ('typ_zaznamu', 'A'), _connector='OR'),
                name='archeologicky_zaznam_typ_zaznamu_check'),
        ),
    ]
