# Generated by Django 3.1.3 on 2021-02-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0001_initial'),
        ('arch_z', '0004_auto_20210215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='akce',
            name='hlavni_vedouci',
            field=models.ForeignKey(db_column='hlavni_vedouci', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.CreateModel(
            name='AkceVedouci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akce', models.ForeignKey(db_column='akce', on_delete=django.db.models.deletion.CASCADE, to='arch_z.akce')),
                ('organizace', models.ForeignKey(blank=True, db_column='organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace')),
                ('vedouci', models.ForeignKey(db_column='vedouci', on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba')),
            ],
            options={
                'db_table': 'akce_vedouci',
                'unique_together': {('akce', 'vedouci')},
            },
        ),
    ]
