# Generated by Django 3.2.11 on 2022-04-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0003_auto_20220310_1543'),
        ('heslar', '0001_initial'),
        ('arch_z', '0004_auto_20220111_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akce',
            name='hlavni_vedouci',
            field=models.ForeignKey(blank=True, db_column='hlavni_vedouci', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AlterField(
            model_name='akce',
            name='specifikace_data',
            field=models.ForeignKey(blank=True, db_column='specifikace_data', limit_choices_to={'nazev_heslare': 27}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_specifikace_data', to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(blank=True, null=True, through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(blank=True, db_column='pristupnost', default=863, limit_choices_to={'nazev_heslare': 25}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
