# Generated by Django 3.2.11 on 2022-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('arch_z', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='katastry',
            field=models.ManyToManyField(blank=True, through='arch_z.ArcheologickyZaznamKatastr', to='heslar.RuianKatastr'),
        ),
    ]
