# Generated by Django 3.2.11 on 2022-11-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0002_auto_20220527_0924'),
        ('arch_z', '0005_alter_archeologickyzaznam_stav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akcevedouci',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(db_column='hlavni_katastr', on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=863, limit_choices_to={'nazev_heslare': 25}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
        migrations.DeleteModel(
            name='Lokalita',
        ),
    ]
