# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.arch_z.migrations.0006_triggers``."""
    initial = True

    dependencies = [
        ("arch_z", "0005_initial"),
    ]

    operations = []

