# Generated by Django 3.1.3 on 2021-02-09 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('arch_z', '0005_auto_20210208_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akce',
            name='final_cj',
        ),
        migrations.RemoveField(
            model_name='archeologickyzaznamkatastr',
            name='hlavni',
        ),
        migrations.RemoveField(
            model_name='lokalita',
            name='final_cj',
        ),
        migrations.AddField(
            model_name='archeologickyzaznam',
            name='hlavni_katastr',
            field=models.ForeignKey(blank=True, db_column='hlavni_katastr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_hlavnich_katastru', to='heslar.ruiankatastr'),
        ),
    ]
