# Generated by Django 3.1.3 on 2021-03-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('arch_z', '0005_auto_20210216_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akce',
            name='datum_ukonceni_v',
        ),
        migrations.RemoveField(
            model_name='akce',
            name='datum_zahajeni_v',
        ),
        migrations.AlterField(
            model_name='akce',
            name='datum_ukonceni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akce',
            name='datum_zahajeni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akce',
            name='hlavni_typ',
            field=models.ForeignKey(blank=True, db_column='hlavni_typ', limit_choices_to={'nazev_heslare': 32}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_hlavni_typy', to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='akce',
            name='specifikace_data',
            field=models.ForeignKey(db_column='specifikace_data', limit_choices_to={'nazev_heslare': 27}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_specifikace_data', to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='akce',
            name='vedlejsi_typ',
            field=models.ForeignKey(blank=True, db_column='vedlejsi_typ', limit_choices_to={'nazev_heslare': 32}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='akce_vedlejsi_typy', to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='archeologickyzaznam',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', default=857, limit_choices_to={'nazev_heslare': 25}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='zaznamy_pristupnosti', to='heslar.heslar'),
        ),
    ]
