# Generated by Django 3.1.3 on 2021-03-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('arch_z', '0006_auto_20210308_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archeologickyzaznamkatastr',
            old_name='archeologicky_zaznam',
            new_name='archeologicky_zaznam_id',
        ),
        migrations.RenameField(
            model_name='archeologickyzaznamkatastr',
            old_name='katastr',
            new_name='katastr_id',
        ),
        migrations.AlterUniqueTogether(
            name='archeologickyzaznamkatastr',
            unique_together={('archeologicky_zaznam_id', 'katastr_id')},
        ),
    ]
