# Generated by Django 3.2.11 on 2022-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_z', '0006_auto_20221109_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akce',
            name='typ',
            field=models.CharField(blank=True, choices=[('R', 'Projektova'), ('N', 'Samostatna')], max_length=1, null=True),
        ),
    ]
