# Generated by Django 3.1.3 on 2021-03-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('arch_z', '0007_auto_20210312_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archeologickyzaznamkatastr',
            old_name='archeologicky_zaznam_id',
            new_name='archeologicky_zaznam',
        ),
        migrations.RenameField(
            model_name='archeologickyzaznamkatastr',
            old_name='katastr_id',
            new_name='katastr',
        ),
        migrations.AlterUniqueTogether(
            name='archeologickyzaznamkatastr',
            unique_together={('archeologicky_zaznam', 'katastr')},
        ),
    ]
