# Generated by Django 3.1.3 on 2021-03-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_z', '0008_auto_20210312_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentacnijednotka',
            name='archeologicky_zaznam',
            field=models.ForeignKey(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam'),
        ),
    ]
