# Generated by Django 3.1.3 on 2021-03-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_z', '0009_auto_20210312_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExterniOdkaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginace', models.TextField(blank=True, null=True)),
                ('archeologicky_zaznam', models.ForeignKey(blank=True, db_column='archeologicky_zaznam', null=True, on_delete=django.db.models.deletion.CASCADE, to='arch_z.archeologickyzaznam')),
            ],
            options={
                'db_table': 'externi_odkaz',
            },
        ),
    ]
