# Generated by Django 4.1.7 on 2023-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch_z", "0009_lokalitasekvence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AkceSekvence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("M", "Morava"), ("C", "Cechy")], max_length=1
                    ),
                ),
                ("sekvence", models.IntegerField()),
            ],
            options={
                "db_table": "akce_sekvence",
            },
        ),
        migrations.AddConstraint(
            model_name="akcesekvence",
            constraint=models.UniqueConstraint(
                fields=("region",), name="unique_sekvence_akce"
            ),
        ),
    ]
