# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.arch_z.migrations.0011_alter_akcevedouci_options`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("arch_z", "0010_akcesekvence_akcesekvence_unique_sekvence_akce"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="akcevedouci",
            options={"ordering": ["vedouci__prijmeni", "vedouci__jmeno"]},
        ),
    ]
