# Generated by Django 3.1.3 on 2021-03-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210315_1307'),
        ('arch_z', '0010_externiodkaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akce',
            name='archeologicky_zaznam',
            field=models.OneToOneField(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='akce', serialize=False, to='arch_z.archeologickyzaznam'),
        ),
        migrations.AlterField(
            model_name='dokumentacnijednotka',
            name='komponenty',
            field=models.ForeignKey(blank=True, db_column='komponenty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komponenty', to='core.komponentavazby'),
        ),
    ]
