# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.arch_z.migrations.0011_alter_akcevedouci_options``."""
    dependencies = [
        ("arch_z", "0010_akcesekvence_akcesekvence_unique_sekvence_akce"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="akcevedouci",
            options={"ordering": ["vedouci__prijmeni", "vedouci__jmeno"]},
        ),
    ]
