# Generated by Django 3.1.3 on 2021-03-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210315_1615'),
        ('arch_z', '0011_auto_20210315_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentacnijednotka',
            name='komponenty',
            field=models.ForeignKey(blank=True, db_column='komponenty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponenty', to='core.komponentavazby'),
        ),
    ]
