# Generated by Django 4.2.8 on 2024-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arch_z", "0011_alter_akcevedouci_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="akce",
            name="vedouci_snapshot",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="archeologickyzaznam",
            name="stav",
            field=models.SmallIntegerField(
                choices=[
                    (1, "arch_z.models.ArcheologickyZaznam.states.AZ1"),
                    (2, "arch_z.models.ArcheologickyZaznam.states.AZ2"),
                    (3, "arch_z.models.ArcheologickyZaznam.states.AZ3"),
                ]
            ),
        ),
    ]
