# Generated by Django 4.2.8 on 2024-02-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historie", "0008_alter_historie_datum_zmeny_alter_historie_poznamka"),
        ("arch_z", "0014_alter_archeologickyzaznam_typ_zaznamu"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="archeologickyzaznam",
            unique_together={("typ_zaznamu", "historie")},
        ),
    ]
