# Generated by Django 4.2.8 on 2024-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_z", "0015_alter_archeologickyzaznam_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="akce",
            name="je_nz",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="akce",
            name="odlozena_nz",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="archeologickyzaznam",
            index=models.Index(
                fields=["stav", "ident_cely"], name="archeologic_stav_237cf4_idx"
            ),
        ),
    ]
