# Generated by Django 5.0.6 on 2024-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_z", "0017_archeologickyzaznam_archeologic_hlavni__e8b941_idx_and_more"),
        ("heslar", "0007_alter_heslar_unique_together_and_more"),
        ("projekt", "0008_alter_projekt_datum_ukonceni_and_more"),
        ("uzivatel", "0015_alter_user_jazyk"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="akce",
            index=models.Index(
                fields=["archeologicky_zaznam", "datum_ukonceni"],
                name="akce_archeol_75782e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="akce",
            index=models.Index(
                fields=["datum_zahajeni", "datum_ukonceni"],
                name="akce_datum_z_d27fb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="akce",
            index=models.Index(
                fields=["datum_zahajeni", "datum_ukonceni", "projekt"],
                name="akce_datum_z_29d66f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="akce",
            index=models.Index(
                fields=["archeologicky_zaznam", "datum_zahajeni", "datum_ukonceni"],
                name="akce_archeol_1a12b6_idx",
            ),
        ),
    ]
