# Generated by Django 5.1.5 on 2025-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.arch_z.migrations.0019_archeologickyzaznam_archeologic_hlavni__edb4d6_idx``."""
    dependencies = [
        ("arch_z", "0018_akce_akce_archeol_75782e_idx_and_more"),
        ("heslar", "0009_alter_heslar_razeni"),
        ("historie", "0009_alter_historie_typ_zmeny"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archeologickyzaznam",
            index=models.Index(
                fields=["hlavni_katastr", "ident_cely", "typ_zaznamu"],
                name="archeologic_hlavni__edb4d6_idx",
            ),
        ),
    ]
