# Generated by Django 3.1.3 on 2021-01-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Historie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum_zmeny", models.DateTimeField(auto_now_add=True)),
                (
                    "typ_zmeny",
                    models.TextField(
                        choices=[
                            ("PX0", "Oznámení projektu"),
                            ("P01", "Schválení oznámení projektu"),
                            ("PX1", "Zapsání projektu"),
                            ("P12", "Přihlášení projektu"),
                            ("P23", "Zahájení v terénu projektu"),
                            ("P34", "Ukončení v terénu projektu"),
                            ("P45", "Uzavření projektu"),
                            ("P*7", "Navržení ke zrušení projektu"),
                            ("P78", "Rušení projektu"),
                            ("P-1", "Vrácení projektu"),
                        ]
                    ),
                ),
                ("poznamka", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "historie",
            },
        ),
        migrations.CreateModel(
            name="HistorieVazby",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ_vazby",
                    models.TextField(
                        choices=[
                            ("projekt", "Projekt"),
                            ("dokument", "Dokument"),
                            ("samostatny_nalez", "Samostatný nález"),
                            ("uzivatel", "Uživatel"),
                            ("pian", "Pian"),
                            ("uzivatel_spoluprace", "Uživatel spolupráce"),
                            ("externi_zdroj", "Externí zdroj"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
            options={
                "db_table": "historie_vazby",
            },
        ),
    ]
