# Generated by Django 3.1.3 on 2021-04-06 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='uzivatel',
            field=models.ForeignKey(db_column='uzivatel', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historie',
            name='vazba',
            field=models.ForeignKey(db_column='vazba', on_delete=django.db.models.deletion.CASCADE, to='historie.historievazby'),
        ),
    ]
