# Generated by Django 3.1.3 on 2021-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historie', '0002_auto_20210215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historievazby',
            name='typ_vazby',
            field=models.TextField(choices=[('projekt', 'Projekt'), ('dokument', 'Dokument'), ('samostatny_nalez', 'Samostatný nález'), ('uzivatel', 'Uživatel'), ('pian', 'Pian'), ('uzivatel_spoluprace', 'Uživatel spolupráce'), ('externi_zdroj', 'Externí zdroj'), ('archeologicky_zaznam', 'Archeologický záznam')], max_length=24),
        ),
    ]
