# Generated by Django 3.1.3 on 2021-01-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historie", "0003_auto_20210122_1902"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historie",
            options={"verbose_name": "historie"},
        ),
        migrations.AlterModelOptions(
            name="historievazby",
            options={"verbose_name": "historie_vazby"},
        ),
    ]
