# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.historie.migrations.0004_alter_historie_options`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("historie", "0003_triggers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historie",
            options={"ordering": ["datum_zmeny"], "verbose_name": "historie"},
        ),
    ]
