# Generated by Django 4.2.8 on 2024-01-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uzivatel", "0009_alter_historicaluser_telefon_alter_user_telefon_and_more"),
        (
            "historie",
            "0006_alter_historie_datum_zmeny_alter_historie_poznamka_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historie",
            name="organizace_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uzivatel.organizace",
            ),
        ),
        migrations.AddIndex(
            model_name="historie",
            index=models.Index(
                fields=["typ_zmeny", "uzivatel", "vazba", "organizace_snapshot"],
                name="historie_typ_zme_326188_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historie",
            index=models.Index(
                fields=["vazba", "organizace_snapshot"],
                name="historie_vazba_746b08_idx",
            ),
        ),
    ]
