# Generated by Django 5.1.2 on 2024-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historie', '0008_alter_historie_datum_zmeny_alter_historie_poznamka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historie',
            name='typ_zmeny',
            field=models.TextField(choices=[('PX0', 'historie.models.historieStav.projekt.Px0'), ('PX0M', 'historie.models.historieStav.projekt.Px0M'), ('P01', 'historie.models.historieStav.projekt.P01'), ('PX1', 'historie.models.historieStav.projekt.Px1'), ('P12', 'historie.models.historieStav.projekt.P12'), ('P23', 'historie.models.historieStav.projekt.P23'), ('P34', 'historie.models.historieStav.projekt.P34'), ('P45', 'historie.models.historieStav.projekt.P45'), ('P56', 'historie.models.historieStav.projekt.P56'), ('P*7', 'historie.models.historieStav.projekt.P*7'), ('P78', 'historie.models.historieStav.projekt.P78'), ('P-1', 'historie.models.historieStav.projekt.P-1'), ('P71', 'historie.models.historieStav.projekt.P71'), ('P81', 'historie.models.historieStav.projekt.P81'), ('P18', 'historie.models.historieStav.projekt.P18'), ('AZ01', 'historie.models.historieStav.az.AZ01'), ('AZ12', 'historie.models.historieStav.az.AZ12'), ('AZ23', 'historie.models.historieStav.az.AZ23'), ('AZ-1', 'historie.models.historieStav.az.AZ-1'), ('AZ-2', 'historie.models.historieStav.az.AZ-2'), ('D01', 'historie.models.historieStav.dokument.D01'), ('D12', 'historie.models.historieStav.dokument.D12'), ('D23', 'historie.models.historieStav.dokument.D23'), ('D-1', 'historie.models.historieStav.dokument.D-1'), ('SN01', 'historie.models.historieStav.sn.SN01'), ('SN12', 'historie.models.historieStav.sn.SN12'), ('SN23', 'historie.models.historieStav.sn.SN23'), ('SN34', 'historie.models.historieStav.sn.SN34'), ('SN-1', 'historie.models.historieStav.sn.SN-1'), ('HR', 'historie.models.historieStav.uzivatel.HR'), ('ZUA', 'historie.models.historieStav.uzivatel.ZUA'), ('AU', 'historie.models.historieStav.uzivatel.ZHA'), ('ZHA', 'historie.models.historieStav.uzivatel.ZUU'), ('ZUU', 'historie.models.historieStav.uzivatel.ZUU'), ('ZHU', 'historie.models.historieStav.uzivatel.ZHU'), ('KAT', 'historie.models.historieStav.katastr.KAT'), ('PI01', 'historie.models.historieStav.pian.PI01'), ('PI12', 'historie.models.historieStav.pian.PI12'), ('SP01', 'historie.models.historieStav.spoluprace.SP01'), ('SP12', 'historie.models.historieStav.spoluprace.SP12'), ('SP-1', 'historie.models.historieStav.spoluprace.SP-1'), ('EZ01', 'historie.models.historieStav.ez.EZ01'), ('EZ12', 'historie.models.historieStav.ez.EZ12'), ('EZ23', 'historie.models.historieStav.ez.EZ23'), ('EZ-1', 'historie.models.historieStav.ez.EZ-1'), ('SBR0', 'historie.models.historieStav.soubor.SBR0')], db_index=True, verbose_name='historie.models.historie.typZmeny.label'),
        ),
    ]
