# Generated by Django 5.2.8 on 2025-12-19 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.historie.migrations.0010_historie_historie_org_lookup_idx`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ('historie', '0009_alter_historie_typ_zmeny'),
        ('uzivatel', '0027_add_notifikace_typ_E-P-11'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historie',
            index=models.Index(fields=['uzivatel'], include=('id',), name='historie_org_lookup_idx'),
        ),
    ]
