# Generated by Django 5.2.10 on 2026-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historie', '0010_historie_historie_org_lookup_idx'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
    ]
