# Generated by Django 3.2.11 on 2022-04-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExterniZdroj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysno', models.TextField(blank=True, null=True)),
                ('nazev', models.TextField(blank=True, null=True)),
                ('edice_rada', models.TextField(blank=True, null=True)),
                ('sbornik_nazev', models.TextField(blank=True, null=True)),
                ('casopis_denik_nazev', models.TextField(blank=True, null=True)),
                ('casopis_rocnik', models.TextField(blank=True, null=True)),
                ('misto', models.TextField(blank=True, null=True)),
                ('vydavatel', models.TextField(blank=True, null=True)),
                ('organizace', models.TextField(blank=True, null=True)),
                ('rok_vydani_vzniku', models.TextField(blank=True, null=True)),
                ('paginace_titulu', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('issn', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('datum_rd', models.TextField(blank=True, null=True)),
                ('stav', models.SmallIntegerField()),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('ident_cely', models.TextField(blank=True, null=True, unique=True)),
                ('final_cj', models.BooleanField()),
            ],
            options={
                'db_table': 'externi_zdroj',
            },
        ),
        migrations.CreateModel(
            name='ExterniZdrojAutor',
            fields=[
                ('externi_zdroj', models.OneToOneField(db_column='externi_zdroj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ez.externizdroj')),
                ('poradi', models.IntegerField()),
            ],
            options={
                'db_table': 'externi_zdroj_autor',
            },
        ),
        migrations.CreateModel(
            name='ExterniZdrojEditor',
            fields=[
                ('externi_zdroj', models.OneToOneField(db_column='externi_zdroj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ez.externizdroj')),
                ('poradi', models.IntegerField()),
            ],
            options={
                'db_table': 'externi_zdroj_editor',
            },
        ),
    ]
