# Generated by Django 3.1.3 on 2021-10-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0001_initial'),
        ('historie', '0001_initial'),
        ('ez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externizdroj',
            name='historie',
            field=models.ForeignKey(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='typ',
            field=models.ForeignKey(db_column='typ', limit_choices_to={'nazev_heslare': 36}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='externi_zroje_typu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='typ_dokumentu',
            field=models.ForeignKey(blank=True, db_column='typ_dokumentu', limit_choices_to={'nazev_heslare': 35}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='externi_zroje_typu_dokumentu', to='heslar.heslar'),
        ),
    ]
