# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historie', '0001_initial'),
        ('ez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externizdroj',
            name='historie',
            field=models.OneToOneField(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='historie.historievazby'),
        ),
    ]
