# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.ez.migrations.0002_externizdroj_historie`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    initial = True

    dependencies = [
        ('ez', '0001_initial'),
        ('historie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externizdroj',
            name='historie',
            field=models.OneToOneField(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.SET_NULL, to='historie.historievazby'),
        ),
    ]
