# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzivatel', '0001_initial'),
        ('ez', '0002_externizdroj_historie'),
        ('heslar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externizdroj',
            name='organizace',
            field=models.ForeignKey(blank=True, db_column='organizace', null=True, on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='typ',
            field=models.ForeignKey(db_column='typ', limit_choices_to={'nazev_heslare': 36}, on_delete=django.db.models.deletion.RESTRICT, related_name='externi_zroje_typu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='typ_dokumentu',
            field=models.ForeignKey(blank=True, db_column='typ_dokumentu', limit_choices_to={'nazev_heslare': 35}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='externi_zroje_typu_dokumentu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='externizdrojeditor',
            name='editor',
            field=models.ForeignKey(db_column='editor', on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='externizdrojautor',
            name='autor',
            field=models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.CASCADE, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='autori',
            field=models.ManyToManyField(related_name='ez_autori', through='ez.ExterniZdrojAutor', to='uzivatel.Osoba'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='editori',
            field=models.ManyToManyField(blank=True, related_name='ez_editori', through='ez.ExterniZdrojEditor', to='uzivatel.Osoba'),
        ),
        migrations.AlterUniqueTogether(
            name='externizdrojeditor',
            unique_together={('poradi', 'externi_zdroj'), ('externi_zdroj', 'editor')},
        ),
        migrations.AlterUniqueTogether(
            name='externizdrojautor',
            unique_together={('externi_zdroj', 'autor'), ('externi_zdroj', 'poradi')},
        ),
    ]
