# Generated by Django 3.2.11 on 2022-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0001_initial'),
        ('ez', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externizdroj',
            name='editori',
            field=models.ManyToManyField(blank=True, related_name='ez_editori', through='ez.ExterniZdrojEditor', to='uzivatel.Osoba'),
        ),
    ]
