# Generated by Django 3.2.11 on 2022-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0004_auto_20221114_2227'),
        ('ez', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externizdroj',
            name='autori',
            field=models.ManyToManyField(related_name='ez_autori', through='ez.ExterniZdrojAutor', to='uzivatel.Osoba'),
        ),
        migrations.AddField(
            model_name='externizdroj',
            name='editori',
            field=models.ManyToManyField(blank=True, null=True, related_name='ez_editori', through='ez.ExterniZdrojEditor', to='uzivatel.Osoba'),
        ),
        migrations.AlterField(
            model_name='externizdroj',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'EZ1 - Zapsána'), (2, 'EZ2 - Odeslána'), (3, 'EZ3 - Potvrzená')]),
        ),
        migrations.AlterField(
            model_name='externizdrojautor',
            name='poradi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='externizdrojeditor',
            name='poradi',
            field=models.IntegerField(null=True),
        ),
    ]
