# Generated by Django 4.1.7 on 2023-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ez", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExterniZdrojSekvence",
            fields=[
                (
                    "id",
                    models.SmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("sekvence", models.IntegerField()),
            ],
            options={
                "db_table": "externi_zdroj_sekvence",
            },
        ),
        migrations.AddConstraint(
            model_name="externizdrojsekvence",
            constraint=models.CheckConstraint(
                check=models.Q(("id", 1)), name="constraint_only_one_sekvence"
            ),
        ),
    ]
