# Generated by Django 3.2.11 on 2022-12-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0002_auto_20221215_1352'),
        ('ez', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externizdroj',
            name='organizace',
            field=models.ForeignKey(blank=True, db_column='organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
    ]
