# Generated by Django 3.2.11 on 2022-11-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ez', '0004_auto_20221121_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externizdroj',
            name='final_cj',
        ),
    ]
