# Generated by Django 4.2.3 on 2023-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ez", "0004_externizdrojsekvence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externizdroj",
            name="stav",
            field=models.SmallIntegerField(
                choices=[(1, "EZ1 - zapsaný"), (2, "Odeslaný"), (3, "EZ2 - potvrzený")]
            ),
        ),
    ]
