# Generated by Django 4.2.7 on 2024-01-30 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ez", "0007_remove_externizdroj_organizace_nazev_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externizdroj",
            old_name="organizace_nazev",
            new_name="organizace",
        ),
    ]
