# Generated by Django 5.1.3 on 2024-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.ez.migrations.0010_externizdroj_doi``."""
    dependencies = [
        ("ez", "0009_alter_externizdroj_datum_rd"),
    ]

    operations = [
        migrations.AddField(
            model_name="externizdroj",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
