# Generated by Django 5.1.5 on 2025-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.ez.migrations.0011_alter_externizdroj_doi``."""
    dependencies = [
        ("ez", "0010_externizdroj_doi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externizdroj",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
