from .base import *

DEBUG = True

ALLOWED_HOSTS = get_secret("ALLOWED_HOSTS").split()
CSRF_TRUSTED_ORIGINS = get_secret("CSRF_TRUSTED_ORIGINS", "").split()

RECAPTCHA_PUBLIC_KEY = get_secret("RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = get_secret("RECAPTCHA_PRIVATE_KEY")

SITE_URL = get_secret("SITE_URL")
DEFAULT_FROM_EMAIL = get_secret("DEFAULT_FROM_EMAIL")
COMPRESS_OFFLINE = True
COMPRESS_ENABLED = True

CLAMD_HOST = get_secret("CLAMD_HOST")
CLAMD_PORT = 3310

