# Generated by Django 3.1.3 on 2021-02-15 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heslar', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soubor',
            name='vlastnik',
            field=models.ForeignKey(db_column='vlastnik', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='areal',
            field=models.ForeignKey(blank=True, db_column='areal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komponenty_arealu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='obdobi',
            field=models.ForeignKey(blank=True, db_column='obdobi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komponenty_obdobi', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='vazba',
            field=models.ForeignKey(blank=True, db_column='vazba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.komponentavazby'),
        ),
    ]
