# Generated by Django 3.1.3 on 2021-03-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('heslar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soubor',
            name='vlastnik',
            field=models.ForeignKey(db_column='vlastnik', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='areal',
            field=models.ForeignKey(blank=True, db_column='areal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komponenty_arealu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='komponenta_vazby',
            field=models.ForeignKey(blank=True, db_column='komponenta_vazby', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komponenty', to='core.komponentavazby'),
        ),
        migrations.AddField(
            model_name='komponenta',
            name='obdobi',
            field=models.ForeignKey(blank=True, db_column='obdobi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='komponenty_obdobi', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='komponentaaktivita',
            name='aktivita',
            field=models.ForeignKey(db_column='aktivita', on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
        migrations.AlterUniqueTogether(
            name='komponentaaktivita',
            unique_together={('komponenta', 'aktivita')},
        ),
    ]
