# Generated by Django 3.1.3 on 2021-03-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenta',
            name='vazba',
            field=models.ForeignKey(blank=True, db_column='vazba', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.komponentavazby'),
        ),
        migrations.AlterField(
            model_name='soubor',
            name='vazba',
            field=models.ForeignKey(db_column='vazba', on_delete=django.db.models.deletion.CASCADE, to='core.souborvazby'),
        ),
    ]
