# Generated by Django 3.2.11 on 2022-03-10 14:43

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historie', '0003_alter_historie_typ_zmeny'),
        ('core', '0002_soubor_vlastnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='soubor',
            name='historie',
            field=models.OneToOneField(db_column='historie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soubor_historie', to='historie.historievazby'),
        ),
        migrations.AlterField(
            model_name='soubor',
            name='path',
            field=models.FileField(default='empty', upload_to=core.models.get_upload_to),
        ),
    ]
