# Generated by Django 3.2.11 on 2023-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soubor',
            name='nazev_puvodni',
        ),
    ]
