# Generated by Django 3.2.11 on 2023-02-09 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soubor',
            name='path',
            field=models.FileField(default='empty', max_length=500, upload_to=core.models.get_upload_to),
        ),
    ]
