# Generated by Django 3.1.3 on 2021-06-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_soubor_vlastnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opravneni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opravneni', models.CharField(choices=[('NIC', 'Nic'), ('VLASTNI', 'Vlastni'), ('ORGANIZACE', 'Organizace'), ('VSE', 'Vse')], default='VLASTNI', max_length=10)),
                ('opravneni_dle_stavu', models.CharField(blank=True, choices=[('DO_STAVU', 'Do Stavu'), ('STAV', 'Stav'), ('OD_STAVU', 'Od Stavu')], max_length=10, null=True)),
                ('aplikace', models.CharField(max_length=50)),
                ('adresa_v_aplikaci', models.CharField(max_length=50)),
                ('skupina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'db_table': 'opravneni',
            },
        ),
    ]
