# Generated by Django 3.2.11 on 2022-12-13 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_soubor_vlastnik"),
    ]

    operations = [
        migrations.AddField(
            model_name="soubor",
            name="size_mb",
            field=models.DecimalField(
                db_column="size_mb", decimal_places=10, max_digits=150
            ),
        ),
        migrations.RemoveField(
            model_name="soubor",
            name="size_bytes",
        ),
    ]
