# Generated by Django 3.2.11 on 2022-07-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soubor_vlastnik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soubor',
            name='typ_souboru',
        ),
    ]
