# Generated by Django 3.1.3 on 2021-03-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210315_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komponenta',
            name='vazba',
        ),
        migrations.AddField(
            model_name='komponenta',
            name='komponenta_vazby',
            field=models.ForeignKey(blank=True, db_column='komponenta_vazby', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.komponentavazby'),
        ),
    ]
