# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_default"),
        ("dokument", "0003_initial"),
        ("projekt", "0004_default"),
    ]

    operations = [
    ]
