# Generated by Django 3.2.11 on 2022-04-12 07:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_remove_soubor_typ_souboru"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdstavkaSystemu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_od", models.DateField()),
                ("datum_odstavky", models.DateField()),
                ("cas_odstavky", models.TimeField()),
                ("text_en", models.TextField()),
                ("text_en", models.TextField()),
            ],
            options={
                "db_table": "odstavky_systemu",
            },
        )
    ]
