# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_default"),
        ("dokument", "0003_initial"),
        ("projekt", "0004_default"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.delete_related_soubor()
                RETURNS trigger
                LANGUAGE 'plpgsql'
                COST 100
                VOLATILE NOT LEAKPROOF
            AS $BODY$
                    BEGIN
                        DELETE FROM soubor AS s
                        WHERE s.vazba = old.soubory
                        ;
                        DELETE FROM soubor_vazby AS s
                        WHERE s.id = old.soubory
                        ;
                        RETURN OLD
                        ;
                    END;    
            $BODY$;
            """,
            reverse_sql="DROP FUNCTION public.delete_related_soubor;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor_dokument BEFORE DELETE ON dokument
                FOR EACH ROW EXECUTE PROCEDURE delete_related_soubor();
            CREATE TRIGGER delete_related_soubor_projekt BEFORE DELETE ON projekt
                FOR EACH ROW EXECUTE PROCEDURE delete_related_soubor();
            """,
            reverse_sql="""
            DROP TRIGGER public.delete_related_soubor_dokument; 
            DROP TRIGGER public.delete_related_soubor_projekt; 
            """,
        ),
    ]
