# Generated by Django 3.1.3 on 2021-03-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('core', '0004_auto_20210315_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomponentaAktivita',
            fields=[
                ('komponenta', models.OneToOneField(db_column='komponenta', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.komponenta')),
                ('aktivita', models.ForeignKey(db_column='aktivita', on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar')),
            ],
            options={
                'db_table': 'komponenta_aktivita',
                'unique_together': {('komponenta', 'aktivita')},
            },
        ),
    ]
