# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_default"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.delete_related_soubor()
                RETURNS trigger
                LANGUAGE 'plpgsql'
                COST 100
                VOLATILE NOT LEAKPROOF
            AS $BODY$
                    BEGIN
                        DELETE FROM soubor AS s
                        WHERE s.vazba = old.id
                        ;
                        RETURN NULL
                        ;
                    END;    
            $BODY$;
            """,
            reverse_sql="DROP FUNCTION public.delete_related_soubor;",
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER delete_related_soubor
                AFTER DELETE
                ON soubor_vazby
                FOR EACH ROW
                EXECUTE FUNCTION delete_related_soubor();
            """,
            reverse_sql="DROP TRIGGER public.delete_related_soubor;",
        ),
    ]
