# Generated by Django 3.2.11 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_odstavka_systemu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odstavkasystemu',
            options={'verbose_name': 'model.odstavka.modelTitle'},
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='cas_odstavky',
            field=models.TimeField(verbose_name='model.odstavka.casOdstavky'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='datum_odstavky',
            field=models.DateField(verbose_name='model.odstavka.datumOdstavky'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='info_od',
            field=models.DateField(verbose_name='model.odstavka.infoOd'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='status',
            field=models.BooleanField(default=True, verbose_name='model.odstavka.status'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='text_cs',
            field=models.TextField(verbose_name='model.odstavka.textcz'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='text_en',
            field=models.TextField(verbose_name='model.odstavka.textEn'),
        ),
    ]
