# Generated by Django 3.1.3 on 2021-03-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_komponentaaktivita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenta',
            name='komponenta_vazby',
            field=models.ForeignKey(blank=True, db_column='komponenta_vazby', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komponenty', to='core.komponentavazby'),
        ),
        migrations.AlterField(
            model_name='soubor',
            name='vazba',
            field=models.ForeignKey(db_column='vazba', on_delete=django.db.models.deletion.CASCADE, related_name='soubory', to='core.souborvazby'),
        ),
    ]
