# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_triggers"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO
            $do$
            BEGIN
                IF EXISTS (
                  SELECT FROM pg_catalog.pg_roles
                  WHERE  rolname = 'cz_archeologickamapa_api_view') THEN
                  RAISE NOTICE 'Role "my_user" already exists. Skipping.';
                ELSE
                  CREATE ROLE cz_archeologickamapa_api_view LOGIN PASSWORD 'never_used_password';
                END IF;
            END
            $do$;
            GRANT SELECT
            ON ALL TABLES
            IN SCHEMA "public"
            TO cz_archeologickamapa_api_view;
            """,
            reverse_sql="""
            REVOKE SELECT
            ON ALL TABLES
            IN SCHEMA "public"
            FROM cz_archeologickamapa_api_view;
            """,
        ),
    ]
