# Generated by Django 3.2.11 on 2022-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221109_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odstavkasystemu',
            options={'verbose_name': 'model.odstavka.modelTitle', 'verbose_name_plural': 'model.odstavka.modelTitle'},
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='text_cs',
            field=models.TextField(verbose_name='base.odstavka.textCS.label'),
        ),
        migrations.AlterField(
            model_name='odstavkasystemu',
            name='text_en',
            field=models.TextField(verbose_name='base.odstavka.textEN.label'),
        ),
    ]
