# Generated by Django 4.1.7 on 2023-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_permissions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="soubor",
            index=models.Index(
                fields=["mimetype"], name="mimetype_idx", opclasses=["text_ops"]
            ),
        ),
    ]
