# Generated by Django 4.1.7 on 2023-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.core.migrations.0007_soubor_mimetype_idx`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("core", "0006_permissions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="soubor",
            index=models.Index(
                fields=["mimetype"], name="mimetype_idx", opclasses=["text_ops"]
            ),
        ),
    ]
