# Generated by Django 4.1.7 on 2023-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_soubor_mimetype_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soubor",
            name="mimetype",
            field=models.TextField(db_index=True),
        ),
    ]
