# Generated by Django 4.1.7 on 2023-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("core", "0009_ident_sequences"),
        ("core", "0010_rename_rada_projektsekvence_region_and_more"),
    ]

    dependencies = [
        ("core", "0008_alter_soubor_mimetype"),
    ]

    operations = [
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.projekt_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.projekt_xident_seq;",
        ),
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.dokument_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.dokument_xident_seq;",
        ),
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.lokalita_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.lokalita_xident_seq;",
        ),
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.pian_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.pian_xident_seq;",
        ),
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.akce_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.akce_xident_seq;",
        ),
        migrations.RunSQL(
            sql="\n            CREATE SEQUENCE IF NOT EXISTS public.externi_zdroj_xident_seq\n            INCREMENT BY 1\n            MINVALUE 1 MAXVALUE 999999999\n            ",
            reverse_sql="DROP SEQUENCE public.externi_zdroj_xident_seq;",
        ),
        migrations.RenameField(
            model_name="projektsekvence",
            old_name="rada",
            new_name="region",
        ),
        migrations.AddConstraint(
            model_name="projektsekvence",
            constraint=models.UniqueConstraint(
                fields=("region", "rok"), name="unique_sekvence_projekt"
            ),
        ),
    ]
