# Generated by Django 4.1.9 on 2023-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.core.migrations.0009_soubor_repository_uuid``."""
    dependencies = [
        ("core", "0008_alter_soubor_mimetype"),
    ]

    operations = [

    ]
