# Generated by Django 4.1.9 on 2023-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_soubor_mimetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="soubor",
            name="repository_uuid",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
