# Generated by Django 4.1.9 on 2023-06-16 15:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_soubor_repository_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soubor",
            name="path",
            field=models.FileField(
                max_length=500, null=True, upload_to=core.models.get_upload_to
            ),
        ),
    ]
