# Generated by Django 4.1.9 on 2023-06-19 17:41

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.core.migrations.0011_merge_0009_ident_sequences_v2_0010_alter_soubor_path``."""
    dependencies = [
        ("core", "0009_ident_sequences_v2"),
        ("core", "0010_alter_soubor_path"),
    ]

    operations = []
