# Generated by Django 4.1.9 on 2023-06-19 17:41

from django.db import migrations


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.core.migrations.0011_merge_0009_ident_sequences_v2_0010_alter_soubor_path`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("core", "0009_ident_sequences_v2"),
        ("core", "0010_alter_soubor_path"),
    ]

    operations = []
