# Generated by Django 4.1.9 on 2023-09-15 15:15

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_merge_0009_ident_sequences_v2_0010_alter_soubor_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAdminSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_group", models.CharField(max_length=100)),
                ("item_id", models.CharField(max_length=100)),
                ("value", models.TextField()),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "custom_admin_settings"
                ),
                models.Model,
            ),
        ),
        migrations.AlterModelOptions(
            name="odstavkasystemu",
            options={
                "verbose_name": "core.model.OdstavkaSystemu.modelTitle.label",
                "verbose_name_plural": "core.model.OdstavkaSystemu.modelTitles.label",
            },
        ),
        migrations.RemoveField(
            model_name="soubor",
            name="repository_uuid",
        ),
        migrations.AlterField(
            model_name="odstavkasystemu",
            name="cas_odstavky",
            field=models.TimeField(
                verbose_name="core.model.OdstavkaSystemu.casOdstavky.label"
            ),
        ),
        migrations.AlterField(
            model_name="odstavkasystemu",
            name="datum_odstavky",
            field=models.DateField(
                verbose_name="core.model.OdstavkaSystemu.datumOdstavky.label"
            ),
        ),
        migrations.AlterField(
            model_name="odstavkasystemu",
            name="info_od",
            field=models.DateField(
                verbose_name="core.model.OdstavkaSystemu.infoOd.label"
            ),
        ),
        migrations.AlterField(
            model_name="odstavkasystemu",
            name="status",
            field=models.BooleanField(
                default=True, verbose_name="core.model.OdstavkaSystemu.status.label"
            ),
        ),
        migrations.AlterField(
            model_name="soubor",
            name="path",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
