# Generated by Django 4.2.3 on 2023-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_soubor_options_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissions",
            name="action",
            field=models.CharField(
                choices=[
                    (
                        "show_adb_edit",
                        "core.models.permissions.actionChoices.show_adb_edit",
                    )
                ],
                max_length=25,
                null=True,
                verbose_name="core.models.permissions.accessibility",
            ),
        ),
    ]
