# Generated by Django 5.1.8 on 2025-04-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.core.migrations.0020_delete_geommigrationjob_and_more``."""
    dependencies = [
        ('core', '0019_alter_permissions_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeomMigrationJob',
        ),
        migrations.DeleteModel(
            name='GeomMigrationJobSJTSKError',
        ),
        migrations.DeleteModel(
            name='GeomMigrationJobWGS84Error',
        ),
    ]
