# Generated by Django 5.2.12 on 2026-04-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_permissions_action'),
        ('pas', '0011_alter_samostatnynalez_projekt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(verbose_name='core.model.apiRequestLog.clientIp')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='core.model.apiRequestLog.receivedAt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='core.model.apiRequestLog.finishedAt')),
                ('request_target', models.CharField(choices=[('samostatny_nalez_xml_import', 'core.model.apiRequestLog.requestTarget.samostatnyNalezXmlImport')], max_length=64, verbose_name='core.model.apiRequestLog.requestTarget')),
                ('filename', models.CharField(blank=True, null=True, max_length=255, verbose_name='core.model.apiRequestLog.filename')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='core.model.apiRequestLog.fileSize')),
                ('status', models.CharField(choices=[('received', 'core.model.apiRequestLog.status.received'), ('processing', 'core.model.apiRequestLog.status.processing'), ('success', 'core.model.apiRequestLog.status.success'), ('failure', 'core.model.apiRequestLog.status.failure')], default='received', max_length=16, verbose_name='core.model.apiRequestLog.status')),
                ('ident_cely', models.CharField(blank=True, max_length=64, verbose_name='core.model.apiRequestLog.identCely')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='core.model.apiRequestLog.errors')),
                ('samostatny_nalez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pas.samostatnynalez', verbose_name='core.model.apiRequestLog.samostatnyNalez')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='core.model.apiRequestLog.user')),
            ],
            options={
                'verbose_name': 'core.model.apiRequestLog.modelTitle.label',
                'verbose_name_plural': 'core.model.apiRequestLog.modelTitles.label',
                'db_table': 'api_log_pozadavku',
                'ordering': ['-received_at'],
            },
        ),
    ]
