# Generated by Django 5.2.12 on 2026-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_apirequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='ident_cely',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='core.model.apiRequestLog.identCely'),
        ),
    ]
