# Generated by Django 6.0.1 on 2026-09-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_permissions_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soubor",
            options={"ordering": ["nazev", "id"]},
        ),
    ]
