# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_permissions_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="odstavkasystemu",
            name="text_cs",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="core.forms.OdstavkaSystemuForm.textCs.label",
            ),
        ),
        migrations.AddField(
            model_name="odstavkasystemu",
            name="text_en",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="core.forms.OdstavkaSystemuForm.textEn.label",
            ),
        ),
    ]
