# Generated by Django 3.1.3 on 2021-04-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekt', '0001_initial'),
        ('oznameni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oznamovatel',
            name='projekt',
            field=models.OneToOneField(db_column='projekt', on_delete=django.db.models.deletion.CASCADE, related_name='oznamovatel', to='projekt.projekt'),
        ),
    ]
