# Generated by Django 3.1.3 on 2022-01-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projekt', '0001_initial'),
        ('oznameni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oznamovatel',
            name='projekt',
            field=models.OneToOneField(db_column='projekt', on_delete=django.db.models.deletion.CASCADE, related_name='oznamovatel', to='projekt.projekt'),
        ),
    ]
