# Generated by Django 4.2.7 on 2024-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.oznameni.migrations.0002_oznamovatel_poznamka`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("oznameni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oznamovatel",
            name="poznamka",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
