# Generated by Django 3.2.11 on 2022-11-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_auto_20220527_0924'),
        ('oznameni', '0002_oznamovatel_projekt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oznamovatel',
            name='id',
        ),
        migrations.AlterField(
            model_name='oznamovatel',
            name='projekt',
            field=models.OneToOneField(db_column='projekt', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='oznamovatel', serialize=False, to='projekt.projekt'),
        ),
    ]
