-- Doplnění vedoucích, co omylem vypadli ještě při migraci z AČR
INSERT INTO  akce_vedouci (akce, organizace, vedouci) VALUES
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-200913257A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Přerostová, Hana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018453A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018455A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018459A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018460A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018461A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201018462A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Chotěbor, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201229086A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Rakovník'), (SELECT id FROM osoba WHERE vypis_cely = 'Blažková, Kateřina')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201229561A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Pleska, Miroslav')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201334621A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Pecinovská, Monika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201448147A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Novák, Miroslav')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201551615A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Novák, Miroslav')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201552434A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Novák, Miroslav')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201662668A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Horník, Pavel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201663029A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Horník, Pavel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-201800827I'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Marešová, Daniela')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100307A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100324A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100325A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100347A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Vlášek, Milan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100372A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100375A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100376A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Hieke, Erik')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100377A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Hieke, Erik')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100378A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Hieke, Erik')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100379A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100404A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Caletka, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100418A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Caletka, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100498A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Hieke, Erik')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100501A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Figura, Jindřich')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100543A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeos'), (SELECT id FROM osoba WHERE vypis_cely = 'Hrubý, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100708A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archaia Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Hrubý, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100718A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZČU Plzeň - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'John, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100901A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Liberec'), (SELECT id FROM osoba WHERE vypis_cely = 'Ouhrabka, Martin')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100915A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Jarošová, Lenka')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100916A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Svoboda, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100917A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Svoboda, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9100988A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Jarošová, Lenka')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101017A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Štěňha, Josef')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101022A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101023A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101195A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101199A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101201A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101230A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101262A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101290A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101292A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101309A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101310A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101311A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101327A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101331A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101446A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101448A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101450A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101460A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101485A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101673A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[samostatný archeolog]'), (SELECT id FROM osoba WHERE vypis_cely = 'Bašta, Jaroslav')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101680A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Procházka, Zdeněk')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101683A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Procházka, Zdeněk')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101684A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Procházka, Zdeněk')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101732A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Čedíková, Eva')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9101748A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Procházka, Zdeněk')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102525A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Pokorný, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102570A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Ústí nad Labem'), (SELECT id FROM osoba WHERE vypis_cely = 'Gabriel, František')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102784A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Tetour, Michal')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102816A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Tetour, Michal')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102836A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum České Budějovice'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102837A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum České Budějovice'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102914A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Přerostová, Hana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102972A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Jirák, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9102976A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Pícka, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103038A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Pícka, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103113A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Klatovy'), (SELECT id FROM osoba WHERE vypis_cely = 'Jirák, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103525A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ÚAPPSZČ Most'), (SELECT id FROM osoba WHERE vypis_cely = 'Sýkora, Milan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103610A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Ústí nad Labem'), (SELECT id FROM osoba WHERE vypis_cely = 'Gabriel, František')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103618A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZČU Plzeň - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chroustovský, Luboš')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103620A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZČU Plzeň - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chroustovský, Luboš')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103751A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'MU Brno - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Drápela, Lukáš')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103878A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'MU Brno - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Havelka, Rudolf')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103879A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'MU Brno - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Drápela, Lukáš')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9103880A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'MU Brno - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Havelka, Rudolf')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104103A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104191A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104229A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104275A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104928A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9104950A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105070A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105076A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Jílek, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105220A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Příbram'), (SELECT id FROM osoba WHERE vypis_cely = 'Marešová, Daniela')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105227A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Kuna, Martin')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105354A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105355A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105366A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105388A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105389A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105427A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105459A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105598A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Písek'), (SELECT id FROM osoba WHERE vypis_cely = 'Adámek, Jan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105599A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Písek'), (SELECT id FROM osoba WHERE vypis_cely = 'Matouš, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105649A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum České Budějovice'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105650A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum České Budějovice'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105723A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105724A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105725A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105726A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105727A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105728A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Tisucká, Marika')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105740A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105769A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Kovář, Daniel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105770A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Kovář, Daniel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105773A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Kovář, Daniel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105827A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105829A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105830A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105831A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105832A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105835A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105838A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105839A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105840A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105841A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105842A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Kovář, Daniel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105870A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Štěrbová, Andrea')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9105947A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Metličková, Jarmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106537A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Metličková, Jarmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106581A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Zelenka, Antonín')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106598A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Štěrbová, Andrea')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106599A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Čedíková, Eva')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106757A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Šmejdová, Martina')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9106952A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Trnka, Robert')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9107291A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Profantová, Naďa')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9107417A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archaia Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Kašpar, Vojtěch')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9107418A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archaia Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Kašpar, Vojtěch')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9107419A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archaia Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Kašpar, Vojtěch')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9107801A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Roztoky'), (SELECT id FROM osoba WHERE vypis_cely = 'Daněček, David')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108014A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Profantová, Naďa')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108027A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Rakovník'), (SELECT id FROM osoba WHERE vypis_cely = 'Pochmanová, Kateřina')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108177A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108187A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108209A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováková, Ludmila')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108210A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'NPÚ ú.o.p. Pardubice'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferstová, Jana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108231A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováček, Karel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108232A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováček, Karel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108233A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováček, Karel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108234A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováček, Karel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108235A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Kočár, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108292A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ZIP Plzeň'), (SELECT id FROM osoba WHERE vypis_cely = 'Nováček, Karel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9108467A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Kalferst, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109041A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Hrubeš, Martin')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109124A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109137A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109162A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109164A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109167A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109205A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109227A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109252A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109256A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109261A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109267A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109269A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109293A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109295A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109296A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109298A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109299A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109303A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109304A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109305A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109308A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109313A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109315A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109326A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109330A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Ernekr, Jaromír')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109337A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109339A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109340A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109341A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109342A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109343A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109351A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109352A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109353A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109355A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109363A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109392A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109397A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109433A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109434A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109435A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109436A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[amatérský spolupracovník]'), (SELECT id FROM osoba WHERE vypis_cely = 'Beneš, Jiří')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109440A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'JČU České Budějovice - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Chvojka, Ondřej')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109445A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Dostál, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109446A'), (SELECT id FROM organizace WHERE nazev_zkraceny = '[jiná organizace]'), (SELECT id FROM osoba WHERE vypis_cely = 'Dostál, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9109891A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Čuláková, Katarína')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110135A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'ÚAPPSZČ Most'), (SELECT id FROM osoba WHERE vypis_cely = 'Gál, Lukáš')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110139A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Chomutov'), (SELECT id FROM osoba WHERE vypis_cely = 'Ondráčková, Lenka')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110140A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Chomutov'), (SELECT id FROM osoba WHERE vypis_cely = 'Ondráčková, Lenka')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110228A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Brno'), (SELECT id FROM osoba WHERE vypis_cely = 'Jarošová, Lenka')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110238A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Česká Lípa'), (SELECT id FROM osoba WHERE vypis_cely = 'Peša, Vladimír')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110657A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Muzeum Hradec Králové'), (SELECT id FROM osoba WHERE vypis_cely = 'Sybr, Pavel')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110793A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Pavlů, Ivan')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110799A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Květina, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110853A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Velímský, Filip')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110864A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Květina, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9110866A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Velímský, Filip')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9111340A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'UK Praha - Filozofická fakulta'), (SELECT id FROM osoba WHERE vypis_cely = 'Sklenářová, Zuzana')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9111440A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Limburský, Petr')),
((SELECT id FROM archeologicky_zaznam WHERE ident_cely = 'C-9162972A'), (SELECT id FROM organizace WHERE nazev_zkraceny = 'Archeologický ústav Praha'), (SELECT id FROM osoba WHERE vypis_cely = 'Vencl, Slavomil'));

-- Zkontrolovat a odstranit nepoužitá jména z hesláře.
with pom AS
(
    SELECT os.id FROM osoba os
    LEFT JOIN adb adb1 ON adb1.autor_popisu = os.id
    LEFT JOIN adb adb2 ON adb2.autor_revize = os.id
    LEFT JOIN akce ak ON ak.hlavni_vedouci = os.id
    LEFT JOIN akce_vedouci av ON av.vedouci = os.id
    LEFT JOIN auth_user au ON au.osoba = os.id
    LEFT JOIN dokument_autor da ON da.autor = os.id
    LEFT JOIN dokument_osoba dos ON dos.osoba = os.id
    LEFT JOIN externi_zdroj_autor ea ON ea.autor = os.id
    LEFT JOIN externi_zdroj_editor ee ON ee.editor = os.id
    LEFT JOIN let l ON l.pozorovatel = os.id
    LEFT JOIN neident_akce_vedouci nv ON nv.vedouci = os.id
    LEFT JOIN projekt pr ON pr.vedouci_projektu = os.id
    LEFT JOIN samostatny_nalez sn ON sn.nalezce = os.id
    WHERE
    adb1.dokumentacni_jednotka is null AND
    adb2.dokumentacni_jednotka is null AND
    ak.archeologicky_zaznam is null AND
    av.id is null AND
    au.id is null AND
    da.id is null AND
    dos.id is null AND
    ea.id is null AND
    ee.id is null AND
    l.id is null AND
    nv.id is null AND
    pr.id is null AND
    sn.id is null
)
DELETE FROM osoba USING pom WHERE osoba.id = pom.id;

-- Vymazání odstraněných hesel z hesláře (opomenuto dříve)
DELETE FROM heslar WHERE ident_cely IN ('HES-000611', 'HES-000616', 'HES-000622');
