# Generated by Django 3.2.11 on 2023-02-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='auth_level',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='email_potvrzen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_potvrzen',
        ),
    ]
