# Generated by Django 3.1.3 on 2022-01-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('heslar', '0001_initial'),
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='hlavni_role',
            field=models.ForeignKey(blank=True, db_column='hlavni_role', db_constraint=False, default=5, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organizace',
            name='typ_organizace',
            field=models.ForeignKey(db_column='typ_organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='typy_organizaci', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='organizace',
            name='zverejneni_pristupnost',
            field=models.ForeignKey(db_column='zverejneni_pristupnost', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organizace_pristupnosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='user',
            name='hlavni_role',
            field=models.ForeignKey(db_column='hlavni_role', default=5, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uzivatele', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizace',
            field=models.ForeignKey(db_column='organizace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
    ]
