# Generated by Django 3.2.11 on 2022-12-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='hlavni_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hlavni_role',
        ),
    ]
