# Generated by Django 3.2.11 on 2023-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0002_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizace',
            name='zanikla',
            field=models.BooleanField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.zanikla'),
        ),
    ]
