# Generated by Django 4.1.7 on 2023-05-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("historie", "0003_triggers"),
        ("uzivatel", "0002_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Uživatel",
                "verbose_name_plural": "historical Uživatelé",
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_vazba",
            field=models.ForeignKey(
                blank=True,
                db_column="historie",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="historie.historievazby",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="organizace",
            field=models.ForeignKey(
                blank=True,
                db_column="organizace",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="uzivatel.organizace",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="history_vazba",
            field=models.OneToOneField(
                db_column="historie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uzivatelhistorievazba",
                to="historie.historievazby",
            ),
        ),
    ]
