# Generated by Django 3.2.11 on 2023-01-10 11:13

from django.db import migrations, models
import uzivatel.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0002_auto_20221215_1352'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationslog',
            name='notificatio_content_d82be3_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_types',
            field=models.ManyToManyField(blank=True, db_table='auth_user_notifikace_typ', default=uzivatel.models.only_notification_groups, limit_choices_to={'ident_cely__icontains': 'S-E-'}, related_name='user', to='uzivatel.UserNotificationType'),
        ),
        migrations.AddIndex(
            model_name='notificationslog',
            index=models.Index(fields=['content_type', 'object_id'], name='notifikace__content_009350_idx'),
        ),
        migrations.AlterModelTable(
            name='notificationslog',
            table='notifikace_log',
        ),
        migrations.AlterModelTable(
            name='usernotificationtype',
            table='notifikace_typ',
        ),
    ]
