# Generated by Django 3.2.11 on 2022-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0002_auto_20220111_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Uživatel'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Přístup do admin. rozhraní'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Globální administrátor'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Přístup do admin. rozhraní'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Globální administrátor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Příjmení'),
        ),
    ]
