# Generated by Django 4.1.7 on 2023-05-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("historie", "0003_triggers"),
        ("uzivatel", "0002_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="history_vazba",
            field=models.OneToOneField(
                db_column="historie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uzivatelhistorievazba",
                to="historie.historievazby",
            ),
        ),
    ]
