# Generated by Django 3.2.11 on 2022-11-09 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('historie', '0002_initial'),
        ('uzivatel', '0002_alter_organizace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='history_vazba',
            field=models.ForeignKey(blank=True, db_column='historie', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='user',
            name='history_vazba',
            field=models.ForeignKey(db_column='historie', null=True, on_delete=django.db.models.fields.related.ForeignKey, related_name='uzivatelhistorievazba', to='historie.historievazby'),
        ),
    ]
