# Generated by Django 4.1.9 on 2023-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0004_alter_osoba_vypis_cely`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("uzivatel", "0003_alter_historicaluser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osoba",
            name="vypis_cely",
            field=models.CharField(
                db_index=True,
                max_length=200,
                verbose_name="uzivatel.models.Osoba.vypis_cely",
            ),
        ),
    ]
