# Generated by Django 3.2.11 on 2022-11-15 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('heslar', '0003_auto_20221115_1214'),
        ('uzivatel', '0003_auto_20221109_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_cely', models.TextField(unique=True)),
                ('zasilat_neaktivnim', models.BooleanField(default=False)),
                ('predmet', models.TextField()),
                ('cesta_sablony', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'uzivatel_notifikace_typ',
            },
        ),
        migrations.AlterModelOptions(
            name='organizace',
            options={'ordering': [django.db.models.functions.comparison.Collate('nazev_zkraceny', 'cs-CZ-x-icu')], 'verbose_name': 'Organizace', 'verbose_name_plural': 'Organizace'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['vypis_cely'], 'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterField(
            model_name='organizace',
            name='adresa',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.adresa'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.email'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='ico',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.ico'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='mesicu_do_zverejneni',
            field=models.IntegerField(default=36, verbose_name='uzivatel.models.Organizace.mesicu_do_zverejneni'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='nazev',
            field=models.TextField(verbose_name='uzivatel.models.Organizace.nazev'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='nazev_en',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.nazev_en'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='nazev_zkraceny',
            field=models.TextField(verbose_name='uzivatel.models.Organizace.nazev_zkraceny'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='nazev_zkraceny_en',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.nazev_zkraceny_en'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='oao',
            field=models.BooleanField(default=False, verbose_name='uzivatel.models.Organizace.oao'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='telefon',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.telefon'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='typ_organizace',
            field=models.ForeignKey(db_column='typ_organizace', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typy_organizaci', to='heslar.heslar', verbose_name='uzivatel.models.Organizace.typ_organizace'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='zanikla',
            field=models.BooleanField(blank=True, null=True, verbose_name='uzivatel.models.Organizace.zanikla'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='zverejneni_pristupnost',
            field=models.ForeignKey(db_column='zverejneni_pristupnost', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizace_pristupnosti', to='heslar.heslar', verbose_name='uzivatel.models.Organizace.zverejneni_pristupnost'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='jmeno',
            field=models.TextField(verbose_name='uzivatel.models.Osoba.jmeno'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='prijmeni',
            field=models.TextField(verbose_name='uzivatel.models.Osoba.prijmeni'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rodne_prijmeni',
            field=models.TextField(blank=True, null=True, verbose_name='uzivatel.models.Osoba.rodne_prijmeni'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rok_narozeni',
            field=models.IntegerField(blank=True, null=True, verbose_name='uzivatel.models.Osoba.rok_narozeni'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='rok_umrti',
            field=models.IntegerField(blank=True, null=True, verbose_name='uzivatel.models.Osoba.rok_umrti'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='vypis',
            field=models.TextField(verbose_name='uzivatel.models.Osoba.vypis'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='vypis_cely',
            field=models.TextField(verbose_name='uzivatel.models.Osoba.vypis_cely'),
        ),
        migrations.CreateModel(
            name='NotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzivatel.usernotificationtype')),
            ],
            options={
                'db_table': 'notifications_log',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='notification_types',
            field=models.ManyToManyField(blank=True, related_name='user', to='uzivatel.UserNotificationType'),
        ),
        migrations.AddIndex(
            model_name='notificationslog',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_d82be3_idx'),
        ),
    ]
