# Generated by Django 4.1.7 on 2023-04-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uzivatel", "0003_alter_organizace_zanikla"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organizace",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("mesicu_do_zverejneni__gte", 0),
                    ("mesicu_do_zverejneni__lte", 1200),
                ),
                name="organizace_mesicu_do_zverejneni_check",
            ),
        ),
    ]
