# Generated by Django 3.2.11 on 2022-11-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('uzivatel', '0004_auto_20221114_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_cely', models.TextField(unique=True)),
                ('zasilat_neaktivnim', models.BooleanField(default=False)),
                ('predmet', models.TextField()),
                ('cesta_sablony', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'uzivatel_notifikace_typ',
            },
        ),
        migrations.CreateModel(
            name='NotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzivatel.usernotificationtype')),
            ],
            options={
                'db_table': 'notifications_log',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='notification_types',
            field=models.ManyToManyField(blank=True, related_name='user', to='uzivatel.UserNotificationType'),
        ),
        migrations.AddIndex(
            model_name='notificationslog',
            index=models.Index(fields=['content_type', 'object_id'], name='notificatio_content_d82be3_idx'),
        ),
    ]
