# Generated by Django 3.2.11 on 2022-11-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20221129_1705'),
        ('uzivatel', '0005_auto_20221121_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizace',
            name='soucast',
            field=models.ForeignKey(blank=True, db_column='soucast', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='typ_organizace',
            field=models.ForeignKey(db_column='typ_organizace', limit_choices_to={'nazev_heslare': 39}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='typy_organizaci', to='heslar.heslar', verbose_name='uzivatel.models.Organizace.typ_organizace'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='zanikla',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='uzivatel.models.Organizace.zanikla'),
        ),
        migrations.AlterField(
            model_name='organizace',
            name='zverejneni_pristupnost',
            field=models.ForeignKey(db_column='zverejneni_pristupnost', limit_choices_to={'nazev_heslare': 25}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizace_pristupnosti', to='heslar.heslar', verbose_name='uzivatel.models.Organizace.zverejneni_pristupnost'),
        ),
    ]
