# Generated by Django 4.2.3 on 2023-08-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0006_remove_notificationslog_notifikace__content_009350_idx_and_more`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("uzivatel", "0005_alter_auth_user_groups_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="jazyk",
            field=models.CharField(
                choices=[
                    ("cs", "core.constants.cs.text"),
                    ("en", "core.constants.cs.text"),
                ],
                default="cs",
                max_length=15,
            ),
        ),
    ]
