# Generated by Django 3.2.11 on 2022-11-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uzivatel', '0006_auto_20221129_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='osoba',
            field=models.ForeignKey(blank=True, db_column='osoba', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='user',
            name='osoba',
            field=models.ForeignKey(blank=True, db_column='osoba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='hlavni_role',
            field=models.ForeignKey(blank=True, db_column='hlavni_role', db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hlavni_role',
            field=models.ForeignKey(db_column='hlavni_role', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uzivatele', to='auth.group'),
        ),
    ]
