# Generated by Django 4.2.3 on 2023-11-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0007_usernotificationtype_text_cs_and_more`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        (
            "uzivatel",
            "0006_remove_notificationslog_notifikace__content_009350_idx_and_more",
        ),
    ]

    operations = []
