# Generated by Django 4.2.3 on 2023-11-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "uzivatel",
            "0006_remove_notificationslog_notifikace__content_009350_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationtype",
            name="text_cs",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usernotificationtype",
            name="text_en",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
