# Generated by Django 4.2.8 on 2024-02-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0009_alter_historicaluser_telefon_alter_user_telefon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotificationtype",
            name="text_cs",
        ),
        migrations.RemoveField(
            model_name="usernotificationtype",
            name="text_en",
        ),
    ]
