# Generated by Django 4.2.11 on 2024-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0010_alter_historicaluser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationslog",
            name="exception",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="notificationslog",
            name="status",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
