# Generated by Django 4.2.11 on 2024-05-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.uzivatel.migrations.0012_delete_historicaluser``."""
    dependencies = [
        ("uzivatel", "0011_notificationslog_exception_notificationslog_status"),
    ]

    operations = [
    ]
