# Generated by Django 4.2.11 on 2024-05-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0012_delete_historicaluser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UzivatelPrihlaseniLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sign_in_date_time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.CharField(max_length=45)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
