# Generated by Django 5.0.6 on 2024-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0014_rename_ip_address_uzivatelprihlasenilog_ip_adresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="jazyk",
            field=models.CharField(
                choices=[
                    ("cs", "core.constants.cs.text"),
                    ("en", "core.constants.en.text"),
                ],
                default="cs",
                max_length=15,
            ),
        ),
    ]
