# Generated by Django 5.0.6 on 2024-06-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0016_organizace_cteni_dokumentu`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("uzivatel", "0015_alter_user_jazyk"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizace",
            name="cteni_dokumentu",
            field=models.BooleanField(
                default=False, verbose_name="uzivatel.models.Organizace.cteni_dokumentu"
            ),
        ),
    ]
