# Generated by Django 5.1.3 on 2024-12-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.uzivatel.migrations.0017_osoba_orcid_osoba_wikidata``."""
    dependencies = [
        ("uzivatel", "0016_organizace_cteni_dokumentu"),
    ]

    operations = [
        migrations.AddField(
            model_name="osoba",
            name="orcid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="osoba",
            name="wikidata",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
