# Generated by Django 5.1.3 on 2024-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0018_organizace_ror`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("uzivatel", "0017_osoba_orcid_osoba_wikidata"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizace",
            name="ror",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
