# Generated by Django 5.1.5 on 2025-02-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.uzivatel.migrations.0019_alter_osoba_orcid``."""
    dependencies = [
        ("uzivatel", "0018_organizace_ror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osoba",
            name="orcid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="wikidata",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
