# Generated by Django 5.1.5 on 2025-02-03 21:37

from django.db import migrations, models

def add_notifikace_typ(apps, schema_editor):
    NotifikaceTyp = apps.get_model('uzivatel', 'UserNotificationType')
    NotifikaceTyp.objects.create(ident_cely='E-N-07')

class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0019_alter_osoba_orcid"),
    ]

    operations = [
        migrations.RunPython(add_notifikace_typ),
    ]