# Generated by Django 5.1.5 on 2025-02-03 21:37

from django.db import migrations, models

def add_notifikace_typ(apps, schema_editor):
    """Zajišťuje logiku funkce ``add_notifikace_typ``.
    
    :param apps: Vstupní hodnota parametru ``apps`` použitého při zpracování.
    :param schema_editor: Vstupní hodnota parametru ``schema_editor`` použitého při zpracování.
    :return: Návratová hodnota funkce po zpracování vstupních dat.
    """
    NotifikaceTyp = apps.get_model('uzivatel', 'UserNotificationType')
    NotifikaceTyp.objects.create(ident_cely='E-N-07')

class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.uzivatel.migrations.0020_add_notifikace_typ_E-N-07``."""
    dependencies = [
        ("uzivatel", "0019_alter_osoba_orcid"),
    ]

    operations = [
        migrations.RunPython(add_notifikace_typ),
    ]