# Generated by Django 5.1.5 on 2025-02-03 21:37

from django.db import migrations, models

def add_notifikace_typ(apps, schema_editor):
    """Funkce `add_notifikace_typ` v modulu `webclient.uzivatel.migrations.0020_add_notifikace_typ_E-N-07`.
    
    Zajišťuje dílčí aplikační logiku pro tento modul.
    
    :param apps: Vstupní hodnota používaná při zpracování.
    :param schema_editor: Vstupní hodnota používaná při zpracování.
    :return: Výsledek odpovídající účelu volání.
    """
    NotifikaceTyp = apps.get_model('uzivatel', 'UserNotificationType')
    NotifikaceTyp.objects.create(ident_cely='E-N-07')

class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0020_add_notifikace_typ_E-N-07`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ("uzivatel", "0019_alter_osoba_orcid"),
    ]

    operations = [
        migrations.RunPython(add_notifikace_typ),
    ]