# Generated by Django 5.2.1 on 2025-07-23 14:34

import django.db.models.deletion
import uzivatel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0011_ruiankraj_email'),
        ('uzivatel', '0023_add_notifikace_typ_E-N-09'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizace',
            name='licence',
            field=models.ForeignKey(default=uzivatel.models.get_default_licence, limit_choices_to={'nazev_heslare': 50}, on_delete=django.db.models.deletion.RESTRICT, related_name='organizace_licence', to='heslar.heslar'),
        ),
    ]
