# Generated by Django 5.2.1 on 2025-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.uzivatel.migrations.0025_organizace_web`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ('uzivatel', '0024_organizace_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizace',
            name='web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='uzivatel.models.Organizace.web'),
        ),
    ]
