# Generated by Django 5.2.10 on 2026-02-18 08:46

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0027_add_notifikace_typ_E-P-11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='uzivatel.models.User.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='uzivatel.models.User.jmeno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='uzivatel.models.User.aktivni'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='uzivatel.models.User.pristupDoAdminRozhrani'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='uzivatel.models.User.globalnyAdministrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jazyk',
            field=models.CharField(choices=[('cs', 'core.constants.cs.text'), ('en', 'core.constants.en.text')], default='cs', max_length=15, verbose_name='uzivatel.models.User.jazyk'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='uzivatel.models.User.prijmeni'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizace',
            field=models.ForeignKey(db_column='organizace', on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.organizace', verbose_name='uzivatel.models.User.organizace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='osoba',
            field=models.ForeignKey(blank=True, db_column='osoba', null=True, on_delete=django.db.models.deletion.RESTRICT, to='uzivatel.osoba', verbose_name='uzivatel.models.User.osoba'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='uzivatel.models.User.heslo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, validators=[core.validators.validate_phone_number], verbose_name='uzivatel.models.User.telefon'),
        ),
    ]
