# Generated by Django 5.2.10 on 2026-02-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0028_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationslog',
            options={'permissions': [('send_test_email', 'Can send test email')]},
        ),
    ]
