# Generated by Django 5.2.14 on 2026-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uzivatel", "0031_lowercase_email_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="datum_potvrzeni_emailu",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="uzivatel.models.User.datumPotvrzeniEmailu",
            ),
        ),
    ]
