# Generated by Django 5.2.14 on 2026-07-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0032_user_datum_potvrzeni_emailu'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationslog',
            name='zaznam_ident_cely',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
