# Generated by Django 3.1.3 on 2021-04-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokument', '0001_initial'),
        ('historie', '0001_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='historie',
            field=models.ForeignKey(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='jazyky',
            field=models.ManyToManyField(related_name='dokumenty_jazyku', through='dokument.DokumentJazyk', to='heslar.Heslar'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='material_originalu',
            field=models.ForeignKey(db_column='material_originalu', limit_choices_to={'nazev_heslare': 12}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_materialu', to='heslar.heslar'),
        ),
    ]
