# Generated by Django 3.1.3 on 2021-02-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historie', '0001_initial'),
        ('heslar', '0001_initial'),
        ('dokument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='historie',
            field=models.ForeignKey(blank=True, db_column='historie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='historie.historievazby'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='material_originalu',
            field=models.ForeignKey(db_column='material_originalu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_materialu', to='heslar.heslar'),
        ),
    ]
