# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokument', '0001_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvar',
            name='tvar',
            field=models.ForeignKey(db_column='tvar', on_delete=django.db.models.deletion.RESTRICT, to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='let',
            name='dohlednost',
            field=models.ForeignKey(db_column='dohlednost', limit_choices_to={'nazev_heslare': 5}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='let_dohlednost', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='let',
            name='letiste_cil',
            field=models.ForeignKey(db_column='letiste_cil', limit_choices_to={'nazev_heslare': 11}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='let_cil', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='let',
            name='letiste_start',
            field=models.ForeignKey(db_column='letiste_start', limit_choices_to={'nazev_heslare': 11}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='let_start', to='heslar.heslar'),
        ),
    ]
