# Generated by Django 3.2.11 on 2022-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('dokument', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='posudky',
            field=models.ManyToManyField(blank=True, related_name='dokumenty_posudku', through='dokument.DokumentPosudek', to='heslar.Heslar'),
        ),
    ]
