# Generated by Django 3.2.11 on 2022-03-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20220111_1144'),
        ('dokument', '0002_auto_20220111_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentcast',
            name='projekt',
            field=models.ForeignKey(blank=True, db_column='projekt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casti_dokumentu', to='projekt.projekt'),
        ),
    ]
