# Generated by Django 3.1.3 on 2021-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokument', '0002_auto_20210215_1659'),
        ('heslar', '0001_initial'),
        ('uzivatel', '0001_initial'),
        ('core', '0002_auto_20210215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='organizace',
            field=models.ForeignKey(db_column='organizace', on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.organizace'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='pristupnost',
            field=models.ForeignKey(db_column='pristupnost', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_pristupnosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='rada',
            field=models.ForeignKey(db_column='rada', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_rady', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='soubory',
            field=models.ForeignKey(blank=True, db_column='soubory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.souborvazby'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='typ_dokumentu',
            field=models.ForeignKey(db_column='typ_dokumentu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_typu_dokumentu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='ulozeni_originalu',
            field=models.ForeignKey(blank=True, db_column='ulozeni_originalu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_ulozeni', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokumentextradata',
            name='format',
            field=models.ForeignKey(blank=True, db_column='format', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_data_formatu', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokumentextradata',
            name='nahrada',
            field=models.ForeignKey(blank=True, db_column='nahrada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_data_nahrad', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokumentextradata',
            name='udalost_typ',
            field=models.ForeignKey(blank=True, db_column='udalost_typ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_data_udalosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokumentextradata',
            name='zachovalost',
            field=models.ForeignKey(blank=True, db_column='zachovalost', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_data_zachovalosti', to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='dokumentextradata',
            name='zeme',
            field=models.ForeignKey(blank=True, db_column='zeme', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_data_zemi', to='heslar.heslar'),
        ),
    ]
