# Generated by Django 3.2.11 on 2022-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20221129_1705'),
        ('dokument', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumentautor',
            options={'ordering': (['poradi'],)},
        ),
        migrations.AddField(
            model_name='dokument',
            name='main_autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='tvary',
            field=models.ManyToManyField(related_name='dokumenty_tvary', through='dokument.Tvar', to='heslar.Heslar'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'D1 - Zapsán'), (2, 'D2 - Odeslán'), (3, 'D3 - Archivován')]),
        ),
    ]
