# Generated by Django 3.1.3 on 2021-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_auto_20210421_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentextradata',
            name='datum_vzniku',
            field=models.DateField(blank=True, null=True),
        ),
    ]
