# Generated by Django 3.2.11 on 2022-05-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='stav',
            field=models.SmallIntegerField(choices=[(1, 'D1 - Zapsán'), (2, 'D2 - Odeslán'), (3, 'D3 - Archivován')]),
        ),
        migrations.AddField(
            model_name="dokument",
            name="main_autor",
            field=models.TextField(blank=True, null=True),
        )
    ]
