# Generated by Django 3.1.3 on 2021-03-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('dokument', '0003_auto_20210317_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentjazyk',
            name='jazyk',
            field=models.ForeignKey(db_column='jazyk', limit_choices_to={'nazev_heslare': 9}, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='dokumentposudek',
            name='posudek',
            field=models.ForeignKey(db_column='posudek', limit_choices_to={'nazev_heslare': 21}, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
    ]
