# Generated by Django 3.2.11 on 2022-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20221129_1705'),
        ('dokument', '0003_alter_dokument_stav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumentautor',
            options={'ordering': (['poradi'],)},
        ),
        migrations.AddField(
            model_name='dokument',
            name='tvary',
            field=models.ManyToManyField(related_name='dokumenty_tvary', through='dokument.Tvar', to='heslar.Heslar'),
        ),
    ]
