# Generated by Django 3.2.11 on 2022-04-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('dokument', '0003_dokumentcast_projekt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='posudky',
            field=models.ManyToManyField(blank=True, null=True, related_name='dokumenty_posudku', through='dokument.DokumentPosudek', to='heslar.Heslar'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='pristupnost',
            field=models.ForeignKey(blank=True, db_column='pristupnost', limit_choices_to={'nazev_heslare': 25}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dokumenty_pristupnosti', to='heslar.heslar'),
        ),
    ]
