# Generated by Django 3.2.11 on 2023-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='hlavni_autor',
        ),
    ]
