# Generated by Django 3.2.11 on 2023-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dokument", "0003_initial"),
        ("neidentakce", "0001_initial"),
    ]

    operations = []
