# Generated by Django 3.1.3 on 2021-03-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('dokument', '0003_auto_20210215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentcast',
            name='dokument',
            field=models.ForeignKey(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, to='dokument.dokument'),
        ),
        migrations.AlterField(
            model_name='dokumentextradata',
            name='dokument',
            field=models.OneToOneField(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dokument.dokument'),
        ),
        migrations.CreateModel(
            name='Tvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('dokument', models.ForeignKey(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, to='dokument.dokument')),
                ('tvar', models.ForeignKey(db_column='tvar', on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar')),
            ],
            options={
                'db_table': 'tvar',
                'unique_together': {('dokument', 'tvar', 'poznamka')},
            },
        ),
    ]
