# Generated by Django 4.1.7 on 2023-05-22 12:29

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0005_alter_dokumentautor_options``."""
    dependencies = [
        ("dokument", "0004_triggers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokumentautor",
            options={"ordering": (["poradi"],)},
        ),
    ]
