# Generated by Django 3.1.3 on 2021-03-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('uzivatel', '0001_initial'),
        ('dokument', '0004_auto_20210315_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentPosudek',
            fields=[
                ('dokument', models.OneToOneField(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dokument.dokument')),
                ('posudek', models.ForeignKey(db_column='posudek', on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar')),
            ],
            options={
                'db_table': 'dokument_posudek',
                'unique_together': {('dokument', 'posudek')},
            },
        ),
        migrations.CreateModel(
            name='DokumentOsoba',
            fields=[
                ('dokument', models.OneToOneField(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dokument.dokument')),
                ('osoba', models.ForeignKey(db_column='osoba', on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba')),
            ],
            options={
                'db_table': 'dokument_osoba',
                'unique_together': {('dokument', 'osoba')},
            },
        ),
        migrations.CreateModel(
            name='DokumentJazyk',
            fields=[
                ('dokument', models.OneToOneField(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dokument.dokument')),
                ('jazyk', models.ForeignKey(db_column='jazyk', on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar')),
            ],
            options={
                'db_table': 'dokument_jazyk',
                'unique_together': {('dokument', 'jazyk')},
            },
        ),
        migrations.CreateModel(
            name='DokumentAutor',
            fields=[
                ('dokument', models.OneToOneField(db_column='dokument', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dokument.dokument')),
                ('poradi', models.IntegerField()),
                ('autor', models.ForeignKey(db_column='autor', on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba')),
            ],
            options={
                'db_table': 'dokument_autor',
                'unique_together': {('dokument', 'autor')},
            },
        ),
    ]
