# Generated by Django 4.2.3 on 2023-09-15 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dokument", "0006_uprava_dokumentsekvence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokumentautor",
            options={"ordering": ("poradi",)},
        ),
        migrations.AlterModelOptions(
            name="let",
            options={"ordering": ["ident_cely"], "verbose_name_plural": "Lety"},
        ),
    ]
