# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0008_alter_tvar_options``."""
    dependencies = [
        ("dokument", "0007_alter_dokumentautor_options_alter_let_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvar",
            options={"ordering": ["tvar__razeni"]},
        ),
    ]
