# Generated by Django 4.2.8 on 2024-02-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heslar", "0006_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
        ("dokument", "0008_alter_tvar_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="licence",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"nazev_heslare": 50},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dokumenty_licence",
                to="heslar.heslar",
            ),
        ),
    ]
