# Generated by Django 4.2.8 on 2024-02-26 21:01

from django.db import migrations

from core.ident_cely import get_heslar_ident
from heslar.hesla import HESLAR_LICENCE


def set_licence_new_value(apps, schema_editor):
    Dokument = apps.get_model('dokument', 'Dokument')
    Heslar = apps.get_model('heslar', 'Heslar')
    HeslarNazev = apps.get_model('heslar', 'HeslarNazev')
    heslar_nazev_licence = HeslarNazev(id=HESLAR_LICENCE, nazev="dokument_licence", povolit_zmeny=True)
    heslar_nazev_licence.save()
    licence_creative_commons = Heslar(heslo="Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní",
                                      heslo_en="Creative Commons Attribution-NonCommercial 4.0 International",
                                      zkratka="CC BY-NC 4.0", zkratka_en="CC BY-NC 4.0", razeni=1,
                                      nazev_heslare=heslar_nazev_licence, ident_cely=get_heslar_ident())
    licence_creative_commons.save()
    licence_neznama = Heslar(heslo="neznámá", heslo_en="unknown", zkratka="neznámá", zkratka_en="unknown", razeni=2,
                             nazev_heslare=heslar_nazev_licence, ident_cely=get_heslar_ident())
    licence_neznama.save()
    pristupnost_neznama = Heslar.objects.get(ident_cely="HES-000868")
    for instance in Dokument.objects.all():
        if instance.organizace.zverejneni_pristupnost == pristupnost_neznama:
            instance.licence_new = licence_neznama
        else:
            instance.licence_new = licence_creative_commons
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dokument", "0009_alter_dokumentextradata_region_and_more"),
    ]

    operations = [
        migrations.RunPython(set_licence_new_value),
    ]
