# Generated by Django 4.2.11 on 2024-04-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heslar", "0006_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
        ("dokument", "0010_alter_dokumentextradata_region_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dokumentextradata",
            old_name="region",
            new_name="region_extra",
        ),
        migrations.AlterField(
            model_name="dokument",
            name="pristupnost",
            field=models.ForeignKey(
                db_column="pristupnost",
                default=865,
                limit_choices_to={"nazev_heslare": 25},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dokumenty_pristupnosti",
                to="heslar.heslar",
            ),
            preserve_default=False,
        ),
    ]
