# Generated by Django 5.0.6 on 2024-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_z", "0017_archeologickyzaznam_archeologic_hlavni__e8b941_idx_and_more"),
        ("dokument", "0011_rename_region_dokumentextradata_region_extra_and_more"),
        ("komponenta", "0002_triggers"),
        ("projekt", "0008_alter_projekt_datum_ukonceni_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokument",
            options={},
        ),
        migrations.AlterField(
            model_name="dokument",
            name="datum_zverejneni",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="oznaceni_originalu",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="dokumentautor",
            name="poradi",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["archeologicky_zaznam", "dokument"],
                name="dokument_ca_archeol_7124b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["projekt", "dokument"], name="dokument_ca_projekt_ef38eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["komponenty", "dokument"], name="dokument_ca_kompone_0a268e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["archeologicky_zaznam", "dokument", "ident_cely"],
                name="dokument_ca_archeol_2f9ff7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["projekt", "dokument", "ident_cely"],
                name="dokument_ca_projekt_eb92b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dokumentcast",
            index=models.Index(
                fields=["komponenty", "dokument", "ident_cely"],
                name="dokument_ca_kompone_d3e701_idx",
            ),
        ),
    ]
