# Generated by Django 5.1.3 on 2024-11-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dokument", "0012_alter_dokument_options_and_more"),
        ("heslar", "0007_alter_heslar_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokumentcast",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
