# Generated by Django 5.1.3 on 2024-12-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0013_dokument_doi_alter_dokument_jazyky_and_more``."""
    dependencies = [
        ("dokument", "0012_alter_dokument_options_and_more"),
        ("heslar", "0008_heslarodkaz_scheme_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="doi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
