# Generated by Django 4.2.8 on 2024-02-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heslar", "0006_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
        ("dokument", "0012_alter_dokumentextradata_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="licence_new",
        ),
        migrations.AlterField(
            model_name="dokument",
            name="licence",
            field=models.ForeignKey(
                limit_choices_to={"nazev_heslare": 45},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dokumenty_licence_temp",
                to="heslar.heslar",
            ),
        ),
    ]
