# Generated by Django 5.1.4 on 2025-01-03 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0013_dokumentextradata_geom_sjtsk_and_more``."""
    dependencies = [
        ("dokument", "0012_alter_dokument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokumentextradata",
            name="geom_sjtsk",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=5514
            ),
        ),
        migrations.AddField(
            model_name="dokumentextradata",
            name="geom_system",
            field=models.CharField(default="4326", max_length=6),
        ),
    ]
