# Generated by Django 5.1.3 on 2025-01-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dokument", "0013_dokument_doi_alter_dokument_jazyky_and_more"),
        ("dokument", "0013_dokumentextradata_geom_sjtsk_and_more"),
    ]

    operations = []
