# Generated by Django 5.1.5 on 2025-02-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0015_alter_dokument_doi_alter_dokument_jazyky_and_more``."""
    dependencies = [
        ("dokument", "0014_merge_20250112_1542"),
        ("heslar", "0009_alter_heslar_razeni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokument",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
