# Generated by Django 5.1.5 on 2025-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0016_alter_dokument_jazyky_alter_dokument_posudky``."""
    dependencies = [
        ('dokument', '0015_alter_dokument_doi_alter_dokument_jazyky_and_more'),
        ('heslar', '0009_alter_heslar_razeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='jazyky',
            field=models.ManyToManyField(limit_choices_to={'nazev_heslare': 9}, related_name='dokumenty_jazyku', through='dokument.DokumentJazyk', to='heslar.heslar'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='posudky',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nazev_heslare': 21}, related_name='dokumenty_posudku', through='dokument.DokumentPosudek', to='heslar.heslar'),
        ),
    ]
