# Generated by Django 5.2 on 2025-10-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.dokument.migrations.0017_alter_tvar_tvar``."""
    dependencies = [
        ("dokument", "0016_alter_dokument_jazyky_alter_dokument_posudky"),
        ("heslar", "0011_ruiankraj_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvar",
            name="tvar",
            field=models.ForeignKey(
                db_column="tvar",
                limit_choices_to={"nazev_heslare": 31},
                on_delete=django.db.models.deletion.RESTRICT,
                to="heslar.heslar",
            ),
        ),
    ]
