# Generated by Django 6.0.1 on 2026-10-02 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokument', '0017_alter_tvar_tvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumentextradata',
            name='pocet_variant_originalu',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dokumentextradata',
            name='sirka',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dokumentextradata',
            name='vyska',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
