# Generated by Django 3.1.3 on 2021-02-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruiankatastr',
            name='soucasny',
        ),
    ]
