# Generated by Django 3.2.11 on 2022-05-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruiankraj',
            options={'ordering': ['nazev']},
        ),
        migrations.AlterModelOptions(
            name='ruianokres',
            options={'ordering': ['nazev']},
        ),
    ]
