# Generated by Django 3.2.11 on 2022-12-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pian', '0001_initial'),
        ('heslar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruiankatastr',
            name='pian',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pian.pian', verbose_name='heslar.models.RuianKatastr.pian'),
        ),
    ]
