# Generated by Django 3.2.11 on 2023-03-27 11:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruiankraj',
            name='nazev_en',
            field=models.TextField(null=True, verbose_name='heslar.models.RuianKraj.nazevEn'),
        ),
        migrations.AlterField(
            model_name='ruianokres',
            name='hranice',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='heslar.models.RuianKatastr.hranice'),
        ),
    ]
