# Generated by Django 3.1.3 on 2021-02-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0002_remove_ruiankatastr_soucasny'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruiankatastr',
            name='soucasny',
            field=models.ForeignKey(blank=True, db_column='soucasny', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.ruiankatastr'),
        ),
    ]
