# Generated by Django 3.2.11 on 2022-11-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0003_auto_20221114_2227'),
        ('heslar', '0003_auto_20221115_1214'),
    ]

    operations = [
    ]
