# Generated by Django 4.1.9 on 2023-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heslar", "0003_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruiankatastr",
            name="kod",
            field=models.IntegerField(
                db_index=True, verbose_name="heslar.models.RuianKatastr.kod"
            ),
        ),
        migrations.AlterField(
            model_name="ruiankatastr",
            name="nazev",
            field=models.TextField(
                db_index=True, verbose_name="heslar.models.RuianKatastr.nazev"
            ),
        ),
    ]
