# Generated by Django 3.2.11 on 2022-11-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0003_auto_20221114_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heslardatace',
            name='obdobi',
            field=models.OneToOneField(db_column='obdobi', limit_choices_to={'nazev_heslare': 15}, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='datace_obdobi', serialize=False, to='heslar.heslar', verbose_name='heslar.models.HeslarDatace.obdobi'),
        ),
        migrations.AlterField(
            model_name='heslarhierarchie',
            name='heslo_nadrazene',
            field=models.ForeignKey(db_column='heslo_nadrazene', on_delete=django.db.models.deletion.PROTECT, related_name='nadrazene', to='heslar.heslar', verbose_name='heslar.models.HeslarHierarchie.heslo_nadrazene'),
        ),
        migrations.AlterField(
            model_name='heslarhierarchie',
            name='typ',
            field=models.TextField(choices=[('podřízenost', 'HeslarHierarchie.TYP_CHOICES.podrizenost'), ('uplatnění', 'HeslarHierarchie.TYP_CHOICES.uplatneni'), ('výchozí hodnota', 'HeslarHierarchie.TYP_CHOICES.vychozi_hodnota')], verbose_name='heslar.models.HeslarHierarchie.typ'),
        ),
    ]
