# Generated by Django 4.2.3 on 2023-09-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("heslar", "0004_alter_ruiankatastr_kod_alter_ruiankatastr_nazev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heslar",
            name="ident_cely",
            field=models.TextField(unique=True, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="heslardatace",
            name="obdobi",
            field=models.OneToOneField(
                db_column="obdobi",
                limit_choices_to={"nazev_heslare": 15},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="datace_obdobi",
                serialize=False,
                to="heslar.heslar",
                verbose_name="Období",
            ),
        ),
        migrations.AlterField(
            model_name="heslardatace",
            name="poznamka",
            field=models.TextField(blank=True, null=True, verbose_name="Poznámka"),
        ),
        migrations.AlterField(
            model_name="heslarhierarchie",
            name="typ",
            field=models.TextField(
                choices=[
                    (
                        "podřízenost",
                        "heslar.models.HeslarHierarchie.TYP_CHOICES.podrizenost",
                    ),
                    (
                        "uplatnění",
                        "heslar.models.HeslarHierarchie.TYP_CHOICES.uplatneni",
                    ),
                    (
                        "výchozí hodnota",
                        "heslar.models.HeslarHierarchie.TYP_CHOICES.vychozi_hodnota",
                    ),
                ],
                verbose_name="heslar.models.HeslarHierarchie.typ",
            ),
        ),
        migrations.AlterField(
            model_name="heslarodkaz",
            name="heslo",
            field=models.ForeignKey(
                db_column="heslo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heslar_odkaz",
                to="heslar.heslar",
                verbose_name="heslar.models.HeslarOdkaz.heslo",
            ),
        ),
        migrations.AlterField(
            model_name="heslarodkaz",
            name="skos_mapping_relation",
            field=models.CharField(
                choices=[
                    ("skos:closeMatch", "skos:closeMatch"),
                    ("skos:exactMatch", "skos:exactMatch"),
                    ("skos:broadMatch", "skos:broadMatch"),
                    ("skos:narrowMatch", "skos:narrowMatch"),
                    ("skos:relatedMatch", "skos:relatedMatch"),
                ],
                max_length=20,
                verbose_name="heslar.models.HeslarOdkaz.skos_mapping_relation",
            ),
        ),
        migrations.AlterField(
            model_name="ruiankatastr",
            name="okres",
            field=models.ForeignKey(
                db_column="okres",
                on_delete=django.db.models.deletion.RESTRICT,
                to="heslar.ruianokres",
                verbose_name="Okres",
            ),
        ),
    ]
