# Generated by Django 4.2.11 on 2024-05-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.heslar.migrations.0007_alter_heslar_unique_together_and_more``."""
    dependencies = [
        ("heslar", "0006_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="heslar",
            unique_together={
                ("nazev_heslare", "heslo_en"),
                ("nazev_heslare", "zkratka"),
                ("nazev_heslare", "heslo"),
            },
        ),
        migrations.RemoveField(
            model_name="heslar",
            name="zkratka_en",
        ),
    ]
