# Generated by Django 5.1.3 on 2024-12-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heslar", "0007_alter_heslar_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heslarodkaz",
            name="scheme_uri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
