# Generated by Django 5.1.5 on 2025-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.heslar.migrations.0009_alter_heslar_razeni``."""
    dependencies = [
        ("heslar", "0008_heslarodkaz_scheme_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heslar",
            name="razeni",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="heslar.models.Heslar.razeni",
            ),
        ),
    ]
