# Generated by Django 5.1.5 on 2025-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0009_alter_heslar_razeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heslar',
            name='razeni',
            field=models.IntegerField(blank=True, null=True, verbose_name='heslar.models.Heslar.razeni'),
        ),
    ]
