# Generated by Django 5.1.8 on 2025-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.heslar.migrations.0011_ruiankraj_email``."""
    dependencies = [
        ('heslar', '0010_alter_heslar_razeni'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruiankraj',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='heslar.models.RuianKraj.email'),
        ),
    ]
