# Generated by Django 3.1.3 on 2021-03-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heslar', '0004_auto_20210308_1235'),
        ('core', '0002_auto_20210215_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nalez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet', models.TextField(blank=True, null=True)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('druh_nalezu', models.ForeignKey(db_column='druh_nalezu', limit_choices_to=models.Q(('nazev_heslare', 22), ('nazev_heslare', 17), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='druh_nalezy', to='heslar.heslar', verbose_name='Druh')),
                ('komponenta', models.ForeignKey(db_column='komponenta', on_delete=django.db.models.deletion.CASCADE, to='core.komponenta')),
                ('specifikace', models.ForeignKey(blank=True, db_column='specifikace', limit_choices_to=models.Q(('nazev_heslare', 28), ('nazev_heslare', 30), _connector='OR'), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar', verbose_name='Specifikace')),
            ],
            options={
                'db_table': 'nalez',
            },
        ),
    ]
