# Generated by Django 4.2.3 on 2023-09-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("heslar", "0005_alter_heslar_ident_cely_alter_heslardatace_obdobi_and_more"),
        ("nalez", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nalezobjekt",
            name="druh",
            field=models.ForeignKey(
                db_column="druh",
                limit_choices_to={"nazev_heslare": 17},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="objekty_druhu",
                to="heslar.heslar",
                verbose_name="Druh",
            ),
        ),
        migrations.AlterField(
            model_name="nalezobjekt",
            name="specifikace",
            field=models.ForeignKey(
                blank=True,
                db_column="specifikace",
                limit_choices_to={"nazev_heslare": 28},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="objekty_specifikace",
                to="heslar.heslar",
                verbose_name="Specifikace",
            ),
        ),
        migrations.AlterField(
            model_name="nalezpredmet",
            name="druh",
            field=models.ForeignKey(
                db_column="druh",
                limit_choices_to={"nazev_heslare": 22},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="predmety_druhu",
                to="heslar.heslar",
                verbose_name="Druh",
            ),
        ),
        migrations.AlterField(
            model_name="nalezpredmet",
            name="specifikace",
            field=models.ForeignKey(
                blank=True,
                db_column="specifikace",
                limit_choices_to={"nazev_heslare": 30},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="predmety_specifikace",
                to="heslar.heslar",
                verbose_name="Specifikace",
            ),
        ),
    ]
