# Generated by Django 3.1.3 on 2021-03-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210316_1727'),
        ('nalez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nalez',
            name='komponenta',
            field=models.ForeignKey(db_column='komponenta', on_delete=django.db.models.deletion.CASCADE, related_name='nalezy', to='core.komponenta'),
        ),
    ]
