# Generated by Django 4.2.3 on 2023-10-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nalez", "0002_alter_nalezobjekt_druh_alter_nalezobjekt_specifikace_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nalezobjekt",
            options={"ordering": ["druh__razeni", "specifikace__razeni"]},
        ),
        migrations.AlterModelOptions(
            name="nalezpredmet",
            options={"ordering": ["druh__razeni", "specifikace__razeni"]},
        ),
    ]
