# Generated by Django 3.2.11 on 2023-02-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_z', '0002_initial'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokalita',
            fields=[
                ('popis', models.TextField(blank=True, null=True)),
                ('nazev', models.TextField()),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('archeologicky_zaznam', models.OneToOneField(db_column='archeologicky_zaznam', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='arch_z.archeologickyzaznam')),
                ('druh', models.ForeignKey(db_column='druh', limit_choices_to={'nazev_heslare': 6}, on_delete=django.db.models.deletion.RESTRICT, related_name='lokalita_druh', to='heslar.heslar')),
                ('jistota', models.ForeignKey(blank=True, db_column='jistota', limit_choices_to={'nazev_heslare': 48}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lokalita_jistota', to='heslar.heslar')),
                ('typ_lokality', models.ForeignKey(db_column='typ_lokality', limit_choices_to={'nazev_heslare': 37}, on_delete=django.db.models.deletion.RESTRICT, related_name='lokalita_typ', to='heslar.heslar')),
                ('zachovalost', models.ForeignKey(blank=True, db_column='zachovalost', limit_choices_to={'nazev_heslare': 49}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lokalita_zachovalost', to='heslar.heslar')),
                ('dalsi_katastry_snapshot', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'lokalita',
            },
        ),
    ]
