# Generated by Django 5.1.3 on 2024-12-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lokalita", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokalita",
            name="igsn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
