# Generated by Django 5.1.5 on 2025-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    """Zapouzdřuje chování třídy ``Migration`` pro modul ``webclient.lokalita.migrations.0003_alter_lokalita_igsn``."""
    dependencies = [
        ('lokalita', '0002_lokalita_igsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokalita',
            name='igsn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
