# Generated by Django 5.2.14 on 2026-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lokalita", "0003_alter_lokalita_igsn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokalita",
            name="nazev",
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
