# Generated by Django 3.2.11 on 2022-04-12 07:35

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzivatel', '0003_auto_20220310_1543'),
        ('dj', '0002_auto_20220111_1144'),
        ('heslar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adb',
            fields=[
                ('dokumentacni_jednotka', models.OneToOneField(db_column='dokumentacni_jednotka', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='adb', serialize=False, to='dj.dokumentacnijednotka')),
                ('ident_cely', models.TextField(unique=True)),
                ('trat', models.TextField()),
                ('parcelni_cislo', models.TextField()),
                ('uzivatelske_oznaceni_sondy', models.TextField(blank=True, null=True)),
                ('stratigraficke_jednotky', models.TextField()),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('cislo_popisne', models.TextField()),
                ('rok_popisu', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)])),
                ('rok_revize', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)])),
                ('autor_popisu', models.ForeignKey(db_column='autor_popisu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='adb_autori_popisu', to='uzivatel.osoba')),
                ('autor_revize', models.ForeignKey(blank=True, db_column='autor_revize', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba')),
                ('podnet', models.ForeignKey(db_column='podnet', limit_choices_to={'nazev_heslare': 20}, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar')),
            ],
            options={
                'db_table': 'adb',
            },
        ),
        migrations.CreateModel(
            name='Kladysm5',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('mapname', models.TextField()),
                ('mapno', models.TextField()),
                ('podil', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=5514)),
                ('cislo', models.TextField()),
            ],
            options={
                'db_table': 'kladysm5',
            },
        ),
        migrations.CreateModel(
            name='VyskovyBod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_cely', models.TextField(unique=True)),
                ('niveleta', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('northing', models.FloatField()),
                ('easting', models.FloatField()),
                ('poradi', models.IntegerField(default=0)),
                ('adb', models.ForeignKey(db_column='adb', on_delete=django.db.models.deletion.CASCADE, related_name='vyskove_body', to='adb.adb')),
                ('typ', models.ForeignKey(db_column='typ', limit_choices_to={'nazev_heslare': 44}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vyskove_body_typu', to='heslar.heslar')),
            ],
            options={
                'db_table': 'vyskovy_bod',
            },
        ),
        migrations.CreateModel(
            name='AdbSekvence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekvence', models.IntegerField()),
                ('kladysm5', models.OneToOneField(db_column='kladysm5_id', on_delete=django.db.models.deletion.DO_NOTHING, to='adb.kladysm5')),
            ],
            options={
                'db_table': 'adb_sekvence',
            },
        ),
        migrations.AddField(
            model_name='adb',
            name='sm5',
            field=models.ForeignKey(db_column='sm5', on_delete=django.db.models.deletion.DO_NOTHING, to='adb.kladysm5'),
        ),
        migrations.AddField(
            model_name='adb',
            name='typ_sondy',
            field=models.ForeignKey(db_column='typ_sondy', limit_choices_to={'nazev_heslare': 42}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='typy_sond_adb', to='heslar.heslar'),
        ),
    ]
