# Generated by Django 3.2.11 on 2022-04-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adb', '0001_initial'),
        ('heslar', '0001_initial'),
        ('uzivatel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adb',
            name='autor_popisu',
            field=models.ForeignKey(db_column='autor_popisu', on_delete=django.db.models.deletion.DO_NOTHING, related_name='adb_autori_popisu', to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='adb',
            name='autor_revize',
            field=models.ForeignKey(blank=True, db_column='autor_revize', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='adb',
            name='podnet',
            field=models.ForeignKey(db_column='podnet', limit_choices_to={'nazev_heslare': 20}, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
        migrations.AddField(
            model_name='adb',
            name='sm5',
            field=models.ForeignKey(db_column='sm5', on_delete=django.db.models.deletion.DO_NOTHING, to='adb.kladysm5'),
        ),
        migrations.AddField(
            model_name='adb',
            name='typ_sondy',
            field=models.ForeignKey(db_column='typ_sondy', limit_choices_to={'nazev_heslare': 42}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='typy_sond_adb', to='heslar.heslar'),
        ),
    ]
