# Generated by Django 3.2.11 on 2022-12-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adb', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vyskovybod',
            name='poradi',
        ),
    ]
