# Generated by Django 3.2.11 on 2022-11-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('adb', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adb',
            name='podnet',
            field=models.ForeignKey(db_column='podnet', limit_choices_to={'nazev_heslare': 20}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='heslar.heslar'),
        ),
    ]
