# Generated by Django 3.2.11 on 2022-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb', '0004_alter_adb_stratigraficke_jednotky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyskovybod',
            name='easting',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vyskovybod',
            name='northing',
            field=models.FloatField(null=True),
        ),
    ]
