# Generated by Django 5.1.5 on 2025-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    """Třída `Migration` v modulu `webclient.adb.migrations.0006_alter_adb_ident_cely`.
    
    Zapouzdřuje související data a chování v rámci dané části aplikace.
    """
    dependencies = [
        ('adb', '0005_alter_adb_ident_cely_alter_adb_rok_popisu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adb',
            name='ident_cely',
            field=models.TextField(unique=True),
        ),
    ]
