# Generated by Django 3.2.11 on 2022-11-18 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb', '0005_auto_20221118_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyskovybod',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=-1),
        ),
        migrations.AlterField(
            model_name='vyskovybod',
            name='poradi',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
