# Generated by Django 3.2.11 on 2022-11-18 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heslar', '0001_initial'),
        ('adb', '0006_auto_20221118_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adb',
            name='typ_sondy',
            field=models.ForeignKey(db_column='typ_sondy', limit_choices_to={'nazev_heslare': 42}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='typy_sond_adb', to='heslar.heslar'),
        ),
    ]
