# Generated by Django 3.2.11 on 2022-12-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzivatel', '0001_initial'),
        ('neidentakce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neidentakcevedouci',
            name='vedouci',
            field=models.ForeignKey(db_column='vedouci', on_delete=django.db.models.deletion.DO_NOTHING, to='uzivatel.osoba'),
        ),
        migrations.AddField(
            model_name='neidentakce',
            name='vedouci',
            field=models.ManyToManyField(blank=True, related_name='neident_akce_vedouci', through='neidentakce.NeidentAkceVedouci', to='uzivatel.Osoba'),
        ),
        migrations.AlterUniqueTogether(
            name='neidentakcevedouci',
            unique_together={('neident_akce', 'vedouci')},
        ),
    ]
