# Generated by Django 3.2.11 on 2022-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzivatel', '0006_auto_20221129_1705'),
        ('neidentakce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neidentakce',
            name='vedouci',
            field=models.ManyToManyField(blank=True, related_name='neident_akce_vedouci', through='neidentakce.NeidentAkceVedouci', to='uzivatel.Osoba'),
        ),
    ]
