# Generated by Django 4.1.7 on 2023-05-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("neidentakce", "0003_auto_20230328_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neidentakcevedouci",
            name="neident_akce",
            field=models.ForeignKey(
                db_column="neident_akce",
                on_delete=django.db.models.deletion.CASCADE,
                to="neidentakce.neidentakce",
            ),
        ),
    ]
