name: Deployment to selected environment
permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      tag:
       description: 'Version tag for deployment (without starting "v", e.g "1.0.0")'
       type: string
       required: true
      environment:
        description: 'Environment'
        type: choice
        options:
          - DEV
          - TEST
        required: true
        default: TEST
      source:
        description: 'Docker image source'
        type: choice
        options:
          - GitHub
          - DockerHub
        required: true
        default: GitHub 

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

env:
  branch: dev
  server_deploy_root: /home/amcr/aiscr-webamcr
  dep_script: scripts/ci_deployment/deploy_server.sh

jobs:
  deployment:
    name: Deploy to ${{ inputs.environment }} Server
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_SERVER: ${{ inputs.environment == 'DEV' && secrets.DEPLOYMENT_SERVER_DEV || inputs.environment == 'TEST' && secrets.DEPLOYMENT_SERVER_TEST }}
      SSH_PRIVATE_KEY: ${{ inputs.environment == 'DEV' && secrets.SSH_PRIVATE_KEY_SERVER_DEV || inputs.environment == 'TEST' && secrets.SSH_PRIVATE_KEY_SERVER_TEST }}
      SSH_KNOWN_HOST: ${{ inputs.environment == 'DEV' && secrets.SSH_KNOWN_HOST_DEV || inputs.environment == 'TEST' && secrets.SSH_KNOWN_HOST_TEST }}
    
    steps:
      - uses: actions/checkout@v6
        with:
          ref: v${{ inputs.tag }}

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn iputils-ping dnsutils          

      - name: Setup VPN config
        id: vpn-config
        run: |
          tmpdir=$(mktemp -d)
          echo "VPN_TMPDIR=$tmpdir" >> $GITHUB_OUTPUT
          cp .github/vpn/openvpn20_huldio_ci.ovpn "$tmpdir/"
          echo "${{ secrets.VPN_CA_CRT }}" > "$tmpdir/openvpn20_huldio_ci_ca.crt"
          echo "${{ secrets.VPN_USER_CRT }}" > "$tmpdir/openvpn20_huldio_ci_user.crt"
          echo "${{ secrets.VPN_USER_KEY }}" > "$tmpdir/openvpn20_huldio_ci_user.key"
          echo "${{ secrets.VPN_SECRET_USERNAME_PASSWORD }}" > "$tmpdir/secret.txt"

      - name: Connect VPN
        run: sudo openvpn --config "${{ steps.vpn-config.outputs.VPN_TMPDIR }}/openvpn20_huldio_ci.ovpn" --auth-user-pass "${{ steps.vpn-config.outputs.VPN_TMPDIR }}/secret.txt"

      - name: Wait for VPN & DNS resolve
        shell: bash
        timeout-minutes: 2
        run: |
          for i in {1..10}; do
            if ping -c 1 ${{ env.DEPLOYMENT_SERVER }}; then
              break
            fi
            sleep 3
          done
          if ! ping -c 1 ${{ env.DEPLOYMENT_SERVER }}; then
            echo "::error::VPN connection failed"
            exit 1
          fi

      - name: SSH connection
        shell: bash
        run: |
          set -euo pipefail
          eval $(ssh-agent -s)
          echo "${{ env.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ env.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          for i in {1..10}; do
            if ping -c 1 ${{ env.DEPLOYMENT_SERVER }}; then break; fi
            sleep 3
          done       
          echo "date_stamp=$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_ENV"          
          git fetch --tags --force
          git rev-parse "v${{ inputs.tag }}" >/dev/null 2>&1 || {
            echo "Tag does not exist"
            exit 1
          }
          ssh amcr@${{ env.DEPLOYMENT_SERVER }} "sudo bash -s" << EOF
          set -euo pipefail
          cd ${{ env.server_deploy_root }}
          git checkout -f v${{ inputs.tag }}
          chmod +x ${{ env.dep_script }}
          ./${{ env.dep_script }} ${{ inputs.tag }} ${{ env.server_deploy_root }} ${{ env.branch }} ${{ inputs.source }}
          EOF

      - name: Disconnect VPN
        if: always()
        run: |
          sudo pkill openvpn || true
