name: Run tests

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      pouzit_predvolenou:
        description: 'Použít předvolenou větev?'
        required: true
        type: boolean

      predvolena_vetv:
        description: 'Vyber předvolenou větev'
        required: false
        type: choice
        options:
          - main
          - develop
          - test

      vlastni_vetv:
        description: 'Zadej vlastní větev (pokud není použita předvolená)'
        required: false
        type: string


env:
  #server_deploy_root: /home/amcr/aiscr-webamcr
  server_deploy_root: /home/havrlant/git/aiscr-webamcr
  dep_script: scripts/ci_deployment/deploy_server.sh
  test_script: scripts/start_selenium_tests.sh

jobs:
  deployment:
    name: Deploy to DEV Server
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn iputils-ping dnsutils          

      - name: Setup VPN config
        run: |
          echo "${{ secrets.VPN_CA_CRT }}" > .github/vpn/openvpn20_huldio_ci_ca.crt
          echo "${{ secrets.VPN_USER_CRT }}" > .github/vpn/openvpn20_huldio_ci_user.crt
          echo "${{ secrets.VPN_USER_KEY }}" > .github/vpn/openvpn20_huldio_ci_user.key
          echo "${{ secrets.VPN_SECRET_USERNAME_PASSWORD }}" > secret.txt

      - name: Connect VPN
        run: sudo openvpn --config ".github/vpn/openvpn20_huldio_ci.ovpn" --daemon --askpass secret.txt

      - name: Wait for VPN & DNS resolve
        shell: bash
        timeout-minutes: 2
        run: |
          for i in {1..10}; do
            dig ${{ secrets.DNS_RESOLVER }} ${{ secrets.DEPLOYMENT_SERVER_DEV }} A +time=1 && break
            sleep 2
          done

      - name: SSH deployment a testy
        shell: bash
        run: |
          vetv="${{ inputs.predvolena_vetv }}"
          if [ "${{ inputs.pouzit_predvolenou }}" != "true" ]; then
            vetv="${{ inputs.vlastni_vetv }}"
          fi
          echo "Použitá větev: $vetv"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY_SERVER_DEV }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOST_DEV }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          sleep 30          
          ping -c 10 ${{ secrets.DEPLOYMENT_SERVER_DEV }}          
          echo "date_stamp=$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_ENV"

          ssh amcr@${{ secrets.DEPLOYMENT_SERVER_DEV }} << 'EOF'
            sudo su - root << 'AOF'
              cd ${{ env.server_deploy_root }}
              chmod +x ${{ env.dep_script }}
              ./${{ env.dep_script }} ${{ env.server_deploy_root }} $vetv

              # Spustit testy
              chmod +x ${{ env.test_script }}
              ./${{ env.test_script }}
            AOF
          EOF

      - name: Stáhnout výsledky testů ze serveru
        run: |
          scp -o StrictHostKeyChecking=no amcr@${{ secrets.DEPLOYMENT_SERVER_DEV }}:/opt/selenium_test/results.xlsx ./results.xlsx

      - name: Nahrát výsledky testů jako artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-vysledky
          path: ./results.xlsx

      - name: Disconnect VPN
        if: always()
        run: |
          sudo killall openvpn
